@echo off
echo Stopping any running Node processes...
taskkill /F /IM node.exe 2>nul
echo Cleaning .next folder...
timeout /t 2 /nobreak >nul
rmdir /s /q .next 2>nul
echo Starting dev server...
npm run dev
