"use client";

import React, { useState, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import MainLayout from "@/components/layout/MainLayout";
import PageHeader from "@/components/shared/PageHeader";
import PageLoader from "@/components/shared/PageLoader";
import { usePageLoad } from "@/hooks/usePageLoad";
import ActionButton from "@/components/shared/ActionButton";
import EmojiPickerPopover from "@/components/shared/EmojiPickerPopover";
import {
  MessageSquare,
  Mail,
  MailOpen,
  Send,
  Search,
  Clock,
  Star,
  Paperclip,
  Plus,
  Inbox,
  Archive,
  Trash2,
  User,
  MoreHorizontal,
  Reply,
  Forward,
  ChevronDown,
  Check,
  Filter,
  Sparkles,
  ArrowLeft,
  X,
} from "lucide-react";
import type { ParentMessage } from "@/types/parent";

// Mock Messages Data
const MOCK_MESSAGES: ParentMessage[] = [
  {
    id: "msg-001",
    senderId: "teacher-001",
    senderName: "Mrs. Nkechi Eze",
    senderRole: "Teacher",
    senderAvatar: "https://i.pravatar.cc/150?u=nkechi",
    subject: "Mathematics Progress Report for Adaeze",
    content: `Dear Mr. Okonkwo,

I hope this message finds you well. I wanted to share some updates about Adaeze's progress in Mathematics this term.

Adaeze has shown remarkable improvement in her mathematical skills, particularly in algebra and geometry. She has been actively participating in class discussions and consistently completes her homework on time.

Key highlights:
- Scored 85% in the mid-term test
- Shows excellent problem-solving abilities
- Helps classmates understand difficult concepts

Areas for improvement:
- Could practice more word problems
- Should work on time management during tests

I believe with continued support at home, Adaeze will excel further. Please feel free to reach out if you have any questions.

Best regards,
Mrs. Nkechi Eze
Mathematics Teacher`,
    timestamp: "2024-01-18T10:30:00Z",
    isRead: false,
    childId: "child-001",
    childName: "Adaeze Okonkwo",
  },
  {
    id: "msg-002",
    senderId: "admin-001",
    senderName: "School Admin",
    senderRole: "Admin",
    subject: "Fee Payment Reminder - 2nd Term",
    content: `Dear Parent/Guardian,

This is a friendly reminder that the school fees for the 2nd Term of the 2024/2025 academic session is due on February 15, 2024.

Please ensure payment is made before the due date to avoid any late fees.

Payment can be made through:
- Bank Transfer
- Card Payment (online)
- Cash at the school bursary

Thank you for your continued support.

Best regards,
School Administration`,
    timestamp: "2024-01-15T09:00:00Z",
    isRead: true,
  },
  {
    id: "msg-003",
    senderId: "principal-001",
    senderName: "Dr. Emmanuel Obi",
    senderRole: "Principal",
    senderAvatar: "https://i.pravatar.cc/150?u=principal",
    subject: "Welcome Back to School - New Term Message",
    content: `Dear Parents,

I hope this message finds you and your families in good health. As we begin the second term of the 2024/2025 academic session, I want to welcome you all back.

This term promises to be exciting with several activities planned:
- Inter-house Sports Competition (February 20th)
- Science Fair (March 5th)
- Cultural Day (March 15th)

I encourage all parents to actively participate in their children's education. Your involvement makes a significant difference in their academic success.

Please don't hesitate to reach out if you have any concerns or suggestions.

Warm regards,
Dr. Emmanuel Obi
Principal`,
    timestamp: "2024-01-08T08:00:00Z",
    isRead: true,
  },
  {
    id: "msg-004",
    senderId: "teacher-002",
    senderName: "Mr. Oluwaseun Adeyemi",
    senderRole: "Teacher",
    senderAvatar: "https://i.pravatar.cc/150?u=oluwaseun",
    subject: "Physics Lab Session Reminder",
    content: `Dear Mr. Okonkwo,

I'm writing to remind you that Chukwuemeka has a physics practical session scheduled for next week Thursday.

Please ensure he comes with:
- Lab coat
- Safety goggles
- Scientific calculator
- Practical notebook

The session will cover electricity and magnetism experiments.

Best regards,
Mr. Oluwaseun Adeyemi
Physics Teacher`,
    timestamp: "2024-01-17T14:20:00Z",
    isRead: false,
    childId: "child-002",
    childName: "Chukwuemeka Okonkwo",
  },
  {
    id: "msg-005",
    senderId: "system",
    senderName: "System Notification",
    senderRole: "System",
    subject: "Attendance Alert - Adaeze Okonkwo",
    content: `This is an automated notification to inform you that Adaeze Okonkwo was marked absent on January 16, 2024.

If this was a planned absence, please contact the school administration with the appropriate documentation.

This message was automatically generated by the school management system.`,
    timestamp: "2024-01-16T09:30:00Z",
    isRead: true,
    childId: "child-001",
    childName: "Adaeze Okonkwo",
  },
];

type FilterType = "all" | "unread" | "starred";

export default function ParentMessagesPage() {
  const isPageLoading = usePageLoad(600);
  const [selectedFilter, setSelectedFilter] = useState<FilterType>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedMessage, setSelectedMessage] = useState<ParentMessage | null>(null);
  const [starredMessages, setStarredMessages] = useState<Set<string>>(new Set());
  const [replyText, setReplyText] = useState("");
  const [showMobileMessage, setShowMobileMessage] = useState(false);

  // Filter messages
  const filteredMessages = useMemo(() => {
    return MOCK_MESSAGES.filter((msg) => {
      const matchesFilter =
        selectedFilter === "all" ||
        (selectedFilter === "unread" && !msg.isRead) ||
        (selectedFilter === "starred" && starredMessages.has(msg.id));
      const matchesSearch =
        searchQuery === "" ||
        msg.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
        msg.senderName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        msg.content.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesFilter && matchesSearch;
    });
  }, [selectedFilter, searchQuery, starredMessages]);

  // Calculate stats
  const stats = useMemo(() => {
    const total = MOCK_MESSAGES.length;
    const unread = MOCK_MESSAGES.filter((m) => !m.isRead).length;
    const starred = starredMessages.size;
    return { total, unread, starred };
  }, [starredMessages]);

  // Toggle star
  const toggleStar = (msgId: string) => {
    setStarredMessages((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(msgId)) {
        newSet.delete(msgId);
      } else {
        newSet.add(msgId);
      }
      return newSet;
    });
  };

  // Get role badge styles
  const getRoleBadgeStyles = (role: ParentMessage["senderRole"]) => {
    const styles = {
      Teacher: {
        bg: "bg-blue-100 dark:bg-blue-900/30",
        text: "text-blue-700 dark:text-blue-400",
        ring: "ring-blue-500/20",
      },
      Admin: {
        bg: "bg-purple-100 dark:bg-purple-900/30",
        text: "text-purple-700 dark:text-purple-400",
        ring: "ring-purple-500/20",
      },
      Principal: {
        bg: "bg-emerald-100 dark:bg-emerald-900/30",
        text: "text-emerald-700 dark:text-emerald-400",
        ring: "ring-emerald-500/20",
      },
      System: {
        bg: "bg-gray-100 dark:bg-gray-700/50",
        text: "text-gray-600 dark:text-gray-400",
        ring: "ring-gray-500/20",
      },
    };
    return styles[role];
  };

  // Format timestamp
  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) {
      return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
    } else if (days === 1) {
      return "Yesterday";
    } else if (days < 7) {
      return date.toLocaleDateString("en-US", { weekday: "short" });
    } else {
      return date.toLocaleDateString("en-GB", { day: "numeric", month: "short" });
    }
  };

  // Format full date
  const formatFullDate = (timestamp: string) => {
    return new Date(timestamp).toLocaleDateString("en-GB", {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  };

  // Handle message selection
  const handleSelectMessage = (message: ParentMessage) => {
    setSelectedMessage(message);
    setShowMobileMessage(true);
  };

  // Handle emoji selection for reply
  const handleEmojiSelect = (emoji: string) => {
    setReplyText((prev) => prev + emoji);
  };

  return (
    <MainLayout>
      <PageLoader isLoading={isPageLoading} loadingText="Loading Messages" />

      <div
        className={`transition-opacity duration-500 ${
          isPageLoading ? "opacity-0" : "opacity-100"
        }`}
      >
        {/* Header Section */}
        <div className="mb-6">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-6">
            <PageHeader
              title="Messages"
              breadcrumbs={[
                { label: "Parent Portal", href: "/parents" },
                { label: "Messages" },
              ]}
            />
            <Link href="/parents/messages/compose">
              <ActionButton
                variant="primary"
                color="blue"
                size="md"
                icon={<Plus className="w-full h-full" />}
              >
                Compose Message
              </ActionButton>
            </Link>
          </div>

          {/* Stats Row */}
          <div className="grid grid-cols-3 gap-4">
            {/* Total Messages */}
            <div className="group relative flex items-center gap-4 p-4 rounded-2xl bg-gradient-to-br from-blue-50/80 to-white dark:from-blue-900/20 dark:to-gray-800/50 border border-blue-100/50 dark:border-blue-800/30 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center shadow-lg shadow-blue-500/20">
                <Inbox className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.total}</p>
                <p className="text-xs font-medium text-blue-600 dark:text-blue-400 uppercase tracking-wide">Total Messages</p>
              </div>
            </div>

            {/* Unread Messages */}
            <div className="group relative flex items-center gap-4 p-4 rounded-2xl bg-gradient-to-br from-red-50/80 to-white dark:from-red-900/20 dark:to-gray-800/50 border border-red-100/50 dark:border-red-800/30 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300">
              <div className="relative">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-red-500 to-rose-600 flex items-center justify-center shadow-lg shadow-red-500/20">
                  <Mail className="w-6 h-6 text-white" />
                </div>
                {stats.unread > 0 && (
                  <span className="absolute -top-1 -right-1 w-5 h-5 bg-red-500 rounded-full flex items-center justify-center text-[10px] font-bold text-white ring-2 ring-white dark:ring-gray-800">
                    {stats.unread}
                  </span>
                )}
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.unread}</p>
                <p className="text-xs font-medium text-red-600 dark:text-red-400 uppercase tracking-wide">Unread</p>
              </div>
            </div>

            {/* Starred Messages */}
            <div className="group relative flex items-center gap-4 p-4 rounded-2xl bg-gradient-to-br from-amber-50/80 to-white dark:from-amber-900/20 dark:to-gray-800/50 border border-amber-100/50 dark:border-amber-800/30 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-amber-500 to-orange-500 flex items-center justify-center shadow-lg shadow-amber-500/20">
                <Star className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.starred}</p>
                <p className="text-xs font-medium text-amber-600 dark:text-amber-400 uppercase tracking-wide">Starred</p>
              </div>
            </div>
          </div>
        </div>

        {/* Main Content - Chat-like Layout */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-sm overflow-hidden">
          <div className="grid grid-cols-1 lg:grid-cols-12 min-h-[600px]">
            {/* Message List Sidebar */}
            <div className={`lg:col-span-4 xl:col-span-4 border-r border-gray-200 dark:border-gray-700 flex flex-col ${showMobileMessage ? "hidden lg:flex" : "flex"}`}>
              {/* Search & Filter Header */}
              <div className="p-4 border-b border-gray-100 dark:border-gray-700/50 space-y-3">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search messages..."
                    className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-gray-50 dark:bg-gray-700/50 border-0 text-gray-900 dark:text-white text-sm placeholder:text-gray-400 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all"
                  />
                </div>

                {/* Filter Pills */}
                <div className="flex gap-2">
                  {[
                    { id: "all", label: "All", count: stats.total },
                    { id: "unread", label: "Unread", count: stats.unread },
                    { id: "starred", label: "Starred", count: stats.starred },
                  ].map((filter) => (
                    <button
                      key={filter.id}
                      onClick={() => setSelectedFilter(filter.id as FilterType)}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all cursor-pointer ${
                        selectedFilter === filter.id
                          ? "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 ring-1 ring-blue-500/20"
                          : "bg-gray-100 dark:bg-gray-700/50 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
                      }`}
                    >
                      {filter.label}
                      {filter.count > 0 && (
                        <span className={`px-1.5 py-0.5 rounded-full text-[10px] ${
                          selectedFilter === filter.id
                            ? "bg-blue-200 dark:bg-blue-800/50 text-blue-800 dark:text-blue-300"
                            : "bg-gray-200 dark:bg-gray-600 text-gray-700 dark:text-gray-300"
                        }`}>
                          {filter.count}
                        </span>
                      )}
                    </button>
                  ))}
                </div>
              </div>

              {/* Messages List */}
              <div className="flex-1 overflow-y-auto">
                {filteredMessages.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-full p-8">
                    <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-700 flex items-center justify-center mb-4">
                      <MessageSquare className="w-8 h-8 text-gray-400" />
                    </div>
                    <p className="text-gray-500 dark:text-gray-400 font-medium">No messages found</p>
                    <p className="text-sm text-gray-400 dark:text-gray-500 mt-1">Try adjusting your filters</p>
                  </div>
                ) : (
                  <div className="divide-y divide-gray-100 dark:divide-gray-700/50">
                    {filteredMessages.map((message) => {
                      const roleStyles = getRoleBadgeStyles(message.senderRole);
                      const isSelected = selectedMessage?.id === message.id;

                      return (
                        <div
                          key={message.id}
                          onClick={() => handleSelectMessage(message)}
                          role="button"
                          tabIndex={0}
                          onKeyDown={(e) => e.key === "Enter" && handleSelectMessage(message)}
                          className={`relative p-4 transition-all cursor-pointer group ${
                            isSelected
                              ? "bg-blue-50/80 dark:bg-blue-900/20"
                              : !message.isRead
                              ? "bg-gradient-to-r from-blue-50/50 to-transparent dark:from-blue-900/10 dark:to-transparent"
                              : "hover:bg-gray-50 dark:hover:bg-gray-700/30"
                          }`}
                        >
                          {/* Selection indicator */}
                          {isSelected && (
                            <div className="absolute left-0 top-0 bottom-0 w-1 bg-blue-500 rounded-r" />
                          )}

                          <div className="flex gap-3">
                            {/* Avatar */}
                            <div className="relative flex-shrink-0">
                              <div className="w-11 h-11 rounded-full overflow-hidden bg-gradient-to-br from-gray-200 to-gray-300 dark:from-gray-600 dark:to-gray-700 ring-2 ring-white dark:ring-gray-800">
                                {message.senderAvatar ? (
                                  <Image
                                    src={message.senderAvatar}
                                    alt={message.senderName}
                                    width={44}
                                    height={44}
                                    className="w-full h-full object-cover"
                                    unoptimized
                                  />
                                ) : (
                                  <div className="w-full h-full flex items-center justify-center">
                                    <User className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                                  </div>
                                )}
                              </div>
                              {/* Online indicator for teachers */}
                              {message.senderRole === "Teacher" && (
                                <div className="absolute -bottom-0.5 -right-0.5 w-3.5 h-3.5 bg-emerald-500 rounded-full ring-2 ring-white dark:ring-gray-800" />
                              )}
                            </div>

                            {/* Content */}
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center justify-between gap-2 mb-0.5">
                                <span className={`text-sm truncate ${
                                  !message.isRead
                                    ? "font-semibold text-gray-900 dark:text-white"
                                    : "font-medium text-gray-700 dark:text-gray-300"
                                }`}>
                                  {message.senderName}
                                </span>
                                <div className="flex items-center gap-1.5 flex-shrink-0">
                                  {!message.isRead && (
                                    <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
                                  )}
                                  <span className="text-[11px] text-gray-500 dark:text-gray-400">
                                    {formatTime(message.timestamp)}
                                  </span>
                                </div>
                              </div>

                              <p className={`text-sm truncate mb-1.5 ${
                                !message.isRead
                                  ? "font-medium text-gray-800 dark:text-gray-200"
                                  : "text-gray-600 dark:text-gray-400"
                              }`}>
                                {message.subject}
                              </p>

                              <div className="flex items-center gap-2">
                                <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-semibold ${roleStyles.bg} ${roleStyles.text} ring-1 ${roleStyles.ring}`}>
                                  {message.senderRole}
                                </span>
                                {message.childName && (
                                  <span className="text-[11px] text-gray-500 dark:text-gray-400 truncate">
                                    {message.childName}
                                  </span>
                                )}
                              </div>
                            </div>

                            {/* Star button */}
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                toggleStar(message.id);
                              }}
                              className={`flex-shrink-0 p-1 rounded-lg transition-all opacity-0 group-hover:opacity-100 ${
                                starredMessages.has(message.id)
                                  ? "opacity-100 text-amber-500"
                                  : "text-gray-300 dark:text-gray-600 hover:text-amber-500"
                              }`}
                            >
                              <Star className={`w-4 h-4 ${starredMessages.has(message.id) ? "fill-current" : ""}`} />
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>

            {/* Message View Panel */}
            <div className={`lg:col-span-8 xl:col-span-8 flex flex-col ${!showMobileMessage ? "hidden lg:flex" : "flex"}`}>
              {selectedMessage ? (
                <>
                  {/* Message Header */}
                  <div className="p-4 lg:p-6 border-b border-gray-100 dark:border-gray-700/50">
                    {/* Mobile back button */}
                    <button
                      onClick={() => setShowMobileMessage(false)}
                      className="lg:hidden flex items-center gap-2 text-gray-600 dark:text-gray-400 mb-4 hover:text-gray-900 dark:hover:text-white transition-colors"
                    >
                      <ArrowLeft className="w-4 h-4" />
                      <span className="text-sm font-medium">Back to messages</span>
                    </button>

                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <h2 className="text-lg lg:text-xl font-bold text-gray-900 dark:text-white mb-3 leading-tight">
                          {selectedMessage.subject}
                        </h2>

                        <div className="flex items-center gap-4">
                          <div className="relative">
                            <div className="w-12 h-12 rounded-full overflow-hidden bg-gradient-to-br from-gray-200 to-gray-300 dark:from-gray-600 dark:to-gray-700 ring-2 ring-white dark:ring-gray-700 shadow-md">
                              {selectedMessage.senderAvatar ? (
                                <Image
                                  src={selectedMessage.senderAvatar}
                                  alt={selectedMessage.senderName}
                                  width={48}
                                  height={48}
                                  className="w-full h-full object-cover"
                                  unoptimized
                                />
                              ) : (
                                <div className="w-full h-full flex items-center justify-center">
                                  <User className="w-6 h-6 text-gray-500" />
                                </div>
                              )}
                            </div>
                          </div>

                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-semibold text-gray-900 dark:text-white">
                                {selectedMessage.senderName}
                              </span>
                              <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-semibold ${getRoleBadgeStyles(selectedMessage.senderRole).bg} ${getRoleBadgeStyles(selectedMessage.senderRole).text}`}>
                                {selectedMessage.senderRole}
                              </span>
                            </div>
                            <p className="text-sm text-gray-500 dark:text-gray-400 flex items-center gap-1">
                              <Clock className="w-3.5 h-3.5" />
                              {formatFullDate(selectedMessage.timestamp)}
                            </p>
                            {selectedMessage.childName && (
                              <p className="text-sm text-blue-600 dark:text-blue-400 mt-0.5 flex items-center gap-1">
                                <User className="w-3.5 h-3.5" />
                                Regarding: {selectedMessage.childName}
                              </p>
                            )}
                          </div>
                        </div>
                      </div>

                      {/* Action buttons */}
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => toggleStar(selectedMessage.id)}
                          className={`p-2 rounded-xl transition-all cursor-pointer ${
                            starredMessages.has(selectedMessage.id)
                              ? "text-amber-500 bg-amber-50 dark:bg-amber-900/20"
                              : "text-gray-400 hover:text-amber-500 hover:bg-gray-100 dark:hover:bg-gray-700"
                          }`}
                        >
                          <Star className={`w-5 h-5 ${starredMessages.has(selectedMessage.id) ? "fill-current" : ""}`} />
                        </button>
                        <button className="p-2 rounded-xl text-gray-400 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 transition-all cursor-pointer">
                          <Archive className="w-5 h-5" />
                        </button>
                        <button className="p-2 rounded-xl text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-all cursor-pointer">
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  </div>

                  {/* Message Body */}
                  <div className="flex-1 overflow-y-auto p-4 lg:p-6">
                    <div className="bg-gray-50 dark:bg-gray-700/30 rounded-2xl p-5 lg:p-6">
                      <div className="prose prose-sm dark:prose-invert max-w-none">
                        {selectedMessage.content.split("\n").map((line, idx) => (
                          <p key={idx} className="mb-2 text-gray-700 dark:text-gray-300 leading-relaxed">
                            {line || <br />}
                          </p>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Reply Section */}
                  <div className="p-4 lg:p-6 border-t border-gray-100 dark:border-gray-700/50 bg-gray-50/50 dark:bg-gray-800/50">
                    <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden">
                      <textarea
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value)}
                        placeholder="Type your reply..."
                        rows={3}
                        className="w-full px-4 py-3 bg-transparent text-gray-900 dark:text-white placeholder:text-gray-400 text-sm resize-none focus:outline-none"
                      />
                      <div className="flex items-center justify-between px-4 py-3 border-t border-gray-100 dark:border-gray-700/50">
                        <div className="flex items-center gap-1">
                          <EmojiPickerPopover
                            onEmojiSelect={handleEmojiSelect}
                            position="top"
                          />
                          <button className="p-2 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors cursor-pointer">
                            <Paperclip className="w-5 h-5" />
                          </button>
                        </div>
                        <ActionButton
                          variant="primary"
                          color="blue"
                          size="sm"
                          icon={<Send className="w-full h-full" />}
                          disabled={!replyText.trim()}
                        >
                          Send Reply
                        </ActionButton>
                      </div>
                    </div>
                  </div>
                </>
              ) : (
                /* Empty State */
                <div className="flex-1 flex flex-col items-center justify-center p-8">
                  <div className="relative mb-6">
                    <div className="absolute inset-0 bg-blue-500/20 rounded-full blur-2xl scale-150 animate-pulse" />
                    <div className="relative w-24 h-24 rounded-full bg-gradient-to-br from-blue-100 to-blue-50 dark:from-blue-900/30 dark:to-blue-800/20 flex items-center justify-center">
                      <MessageSquare className="w-12 h-12 text-blue-500 dark:text-blue-400" />
                    </div>
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
                    Select a message
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center max-w-xs mb-6">
                    Choose a message from the list to view its contents and reply
                  </p>
                  <div className="flex items-center gap-2 text-sm text-blue-600 dark:text-blue-400">
                    <Sparkles className="w-4 h-4" />
                    <span>{stats.unread} unread messages waiting</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
