"use client";

import React, { useState, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import MainLayout from "@/components/layout/MainLayout";
import PageHeader from "@/components/shared/PageHeader";
import PageLoader from "@/components/shared/PageLoader";
import { usePageLoad } from "@/hooks/usePageLoad";
import StatCard from "@/components/shared/StatCard";
import Button from "@/components/shared/Button";
import {
  MessageSquare,
  Mail,
  MailOpen,
  Send,
  Search,
  ChevronRight,
  Clock,
  Star,
  Paperclip,
  Filter,
  Plus,
  Inbox,
  Archive,
  Trash2,
  User,
} from "lucide-react";
import type { ParentMessage } from "@/types/parent";

// Mock Messages Data
const MOCK_MESSAGES: ParentMessage[] = [
  {
    id: "msg-001",
    senderId: "teacher-001",
    senderName: "Mrs. Nkechi Eze",
    senderRole: "Teacher",
    senderAvatar: "https://i.pravatar.cc/150?u=nkechi",
    subject: "Mathematics Progress Report for Adaeze",
    content: `Dear Mr. Okonkwo,

I hope this message finds you well. I wanted to share some updates about Adaeze's progress in Mathematics this term.

Adaeze has shown remarkable improvement in her mathematical skills, particularly in algebra and geometry. She has been actively participating in class discussions and consistently completes her homework on time.

Key highlights:
- Scored 85% in the mid-term test
- Shows excellent problem-solving abilities
- Helps classmates understand difficult concepts

Areas for improvement:
- Could practice more word problems
- Should work on time management during tests

I believe with continued support at home, Adaeze will excel further. Please feel free to reach out if you have any questions.

Best regards,
Mrs. Nkechi Eze
Mathematics Teacher`,
    timestamp: "2024-01-18T10:30:00Z",
    isRead: false,
    childId: "child-001",
    childName: "Adaeze Okonkwo",
  },
  {
    id: "msg-002",
    senderId: "admin-001",
    senderName: "School Admin",
    senderRole: "Admin",
    subject: "Fee Payment Reminder - 2nd Term",
    content: `Dear Parent/Guardian,

This is a friendly reminder that the school fees for the 2nd Term of the 2024/2025 academic session is due on February 15, 2024.

Please ensure payment is made before the due date to avoid any late fees.

Payment can be made through:
- Bank Transfer
- Card Payment (online)
- Cash at the school bursary

Thank you for your continued support.

Best regards,
School Administration`,
    timestamp: "2024-01-15T09:00:00Z",
    isRead: true,
  },
  {
    id: "msg-003",
    senderId: "principal-001",
    senderName: "Dr. Emmanuel Obi",
    senderRole: "Principal",
    senderAvatar: "https://i.pravatar.cc/150?u=principal",
    subject: "Welcome Back to School - New Term Message",
    content: `Dear Parents,

I hope this message finds you and your families in good health. As we begin the second term of the 2024/2025 academic session, I want to welcome you all back.

This term promises to be exciting with several activities planned:
- Inter-house Sports Competition (February 20th)
- Science Fair (March 5th)
- Cultural Day (March 15th)

I encourage all parents to actively participate in their children's education. Your involvement makes a significant difference in their academic success.

Please don't hesitate to reach out if you have any concerns or suggestions.

Warm regards,
Dr. Emmanuel Obi
Principal`,
    timestamp: "2024-01-08T08:00:00Z",
    isRead: true,
  },
  {
    id: "msg-004",
    senderId: "teacher-002",
    senderName: "Mr. Oluwaseun Adeyemi",
    senderRole: "Teacher",
    senderAvatar: "https://i.pravatar.cc/150?u=oluwaseun",
    subject: "Physics Lab Session Reminder",
    content: `Dear Mr. Okonkwo,

I'm writing to remind you that Chukwuemeka has a physics practical session scheduled for next week Thursday.

Please ensure he comes with:
- Lab coat
- Safety goggles
- Scientific calculator
- Practical notebook

The session will cover electricity and magnetism experiments.

Best regards,
Mr. Oluwaseun Adeyemi
Physics Teacher`,
    timestamp: "2024-01-17T14:20:00Z",
    isRead: false,
    childId: "child-002",
    childName: "Chukwuemeka Okonkwo",
  },
  {
    id: "msg-005",
    senderId: "system",
    senderName: "System Notification",
    senderRole: "System",
    subject: "Attendance Alert - Adaeze Okonkwo",
    content: `This is an automated notification to inform you that Adaeze Okonkwo was marked absent on January 16, 2024.

If this was a planned absence, please contact the school administration with the appropriate documentation.

This message was automatically generated by the school management system.`,
    timestamp: "2024-01-16T09:30:00Z",
    isRead: true,
    childId: "child-001",
    childName: "Adaeze Okonkwo",
  },
];

type FilterType = "all" | "unread" | "starred";

export default function ParentMessagesPage() {
  const isPageLoading = usePageLoad(600);
  const [selectedFilter, setSelectedFilter] = useState<FilterType>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedMessage, setSelectedMessage] = useState<ParentMessage | null>(null);
  const [starredMessages, setStarredMessages] = useState<Set<string>>(new Set());

  // Filter messages
  const filteredMessages = useMemo(() => {
    return MOCK_MESSAGES.filter((msg) => {
      const matchesFilter =
        selectedFilter === "all" ||
        (selectedFilter === "unread" && !msg.isRead) ||
        (selectedFilter === "starred" && starredMessages.has(msg.id));
      const matchesSearch =
        searchQuery === "" ||
        msg.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
        msg.senderName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        msg.content.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesFilter && matchesSearch;
    });
  }, [selectedFilter, searchQuery, starredMessages]);

  // Calculate stats
  const stats = useMemo(() => {
    const total = MOCK_MESSAGES.length;
    const unread = MOCK_MESSAGES.filter((m) => !m.isRead).length;
    const starred = starredMessages.size;
    return { total, unread, starred };
  }, [starredMessages]);

  // Toggle star
  const toggleStar = (msgId: string) => {
    setStarredMessages((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(msgId)) {
        newSet.delete(msgId);
      } else {
        newSet.add(msgId);
      }
      return newSet;
    });
  };

  // Get role badge color
  const getRoleBadgeColor = (role: ParentMessage["senderRole"]) => {
    const colors = {
      Teacher: "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400",
      Admin: "bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400",
      Principal: "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400",
      System: "bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400",
    };
    return colors[role];
  };

  // Format timestamp
  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) {
      return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
    } else if (days === 1) {
      return "Yesterday";
    } else if (days < 7) {
      return date.toLocaleDateString("en-US", { weekday: "short" });
    } else {
      return date.toLocaleDateString("en-GB", { day: "numeric", month: "short" });
    }
  };

  return (
    <MainLayout>
      <PageLoader isLoading={isPageLoading} loadingText="Loading Messages" />

      <div
        className={`space-y-6 transition-opacity duration-500 ${
          isPageLoading ? "opacity-0" : "opacity-100"
        }`}
      >
        {/* Header */}
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <PageHeader
            title="Messages"
            breadcrumbs={[
              { label: "Parent Portal", href: "/parents" },
              { label: "Messages" },
            ]}
          />
          <Link href="/parents/messages/compose">
            <Button variant="primary">
              <Plus className="w-4 h-4 mr-2" />
              Compose Message
            </Button>
          </Link>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-3 sm:gap-4">
          <StatCard
            icon={Inbox}
            label="Total Messages"
            value={stats.total.toString()}
            color="blue"
          />
          <StatCard
            icon={Mail}
            label="Unread"
            value={stats.unread.toString()}
            color={stats.unread > 0 ? "red" : "green"}
            badge={stats.unread > 0 ? "New" : undefined}
          />
          <StatCard
            icon={Star}
            label="Starred"
            value={stats.starred.toString()}
            color="yellow"
          />
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Message List */}
          <div className="lg:col-span-1 space-y-4">
            {/* Search & Filter */}
            <div className="space-y-3">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search messages..."
                  className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"
                />
              </div>
              <div className="flex gap-1 p-1 bg-gray-100 dark:bg-gray-800 rounded-lg">
                {[
                  { id: "all", label: "All", icon: Inbox },
                  { id: "unread", label: "Unread", icon: Mail },
                  { id: "starred", label: "Starred", icon: Star },
                ].map((filter) => {
                  const Icon = filter.icon;
                  return (
                    <button
                      key={filter.id}
                      onClick={() => setSelectedFilter(filter.id as FilterType)}
                      className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-md text-sm font-medium transition-all ${
                        selectedFilter === filter.id
                          ? "bg-white dark:bg-gray-700 text-blue-600 dark:text-blue-400 shadow-sm"
                          : "text-gray-600 dark:text-gray-400 hover:bg-white/50 dark:hover:bg-gray-700/50"
                      }`}
                    >
                      <Icon className="w-4 h-4" />
                      {filter.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Message List */}
            <div className="bg-white dark:bg-gray-800 midnight:bg-gray-900 purple:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-700 midnight:border-cyan-500/20 purple:border-pink-500/20 shadow-sm overflow-hidden">
              <div className="max-h-[600px] overflow-y-auto">
                {filteredMessages.length === 0 ? (
                  <div className="p-8 text-center">
                    <MessageSquare className="w-12 h-12 text-gray-300 dark:text-gray-600 mx-auto mb-3" />
                    <p className="text-gray-500 dark:text-gray-400">No messages found</p>
                  </div>
                ) : (
                  filteredMessages.map((message) => (
                    <button
                      key={message.id}
                      onClick={() => setSelectedMessage(message)}
                      className={`w-full text-left p-4 border-b border-gray-100 dark:border-gray-700 last:border-b-0 transition-all hover:bg-gray-50 dark:hover:bg-gray-700/50 ${
                        selectedMessage?.id === message.id
                          ? "bg-blue-50 dark:bg-blue-900/20"
                          : !message.isRead
                          ? "bg-blue-50/50 dark:bg-blue-900/10"
                          : ""
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <div className="relative w-10 h-10 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700 flex-shrink-0">
                          {message.senderAvatar ? (
                            <Image
                              src={message.senderAvatar}
                              alt={message.senderName}
                              fill
                              className="object-cover"
                              unoptimized
                            />
                          ) : (
                            <div className="w-full h-full flex items-center justify-center">
                              <User className="w-5 h-5 text-gray-500" />
                            </div>
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between gap-2 mb-1">
                            <p className={`text-sm truncate ${!message.isRead ? "font-semibold text-gray-900 dark:text-white" : "font-medium text-gray-700 dark:text-gray-300"}`}>
                              {message.senderName}
                            </p>
                            <div className="flex items-center gap-1.5 flex-shrink-0">
                              {!message.isRead && (
                                <span className="w-2 h-2 rounded-full bg-blue-500" />
                              )}
                              <span className="text-xs text-gray-500 dark:text-gray-400">
                                {formatTime(message.timestamp)}
                              </span>
                            </div>
                          </div>
                          <p className={`text-sm truncate mb-1 ${!message.isRead ? "font-medium text-gray-800 dark:text-gray-200" : "text-gray-600 dark:text-gray-400"}`}>
                            {message.subject}
                          </p>
                          <div className="flex items-center gap-2">
                            <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${getRoleBadgeColor(message.senderRole)}`}>
                              {message.senderRole}
                            </span>
                            {message.childName && (
                              <span className="text-xs text-gray-500 dark:text-gray-400">
                                • {message.childName}
                              </span>
                            )}
                          </div>
                        </div>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleStar(message.id);
                          }}
                          className={`p-1 rounded transition-colors ${
                            starredMessages.has(message.id)
                              ? "text-yellow-500"
                              : "text-gray-300 dark:text-gray-600 hover:text-yellow-500"
                          }`}
                        >
                          <Star className={`w-4 h-4 ${starredMessages.has(message.id) ? "fill-current" : ""}`} />
                        </button>
                      </div>
                    </button>
                  ))
                )}
              </div>
            </div>
          </div>

          {/* Message View */}
          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 midnight:bg-gray-900 purple:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-700 midnight:border-cyan-500/20 purple:border-pink-500/20 shadow-sm overflow-hidden h-full">
              {selectedMessage ? (
                <div className="h-full flex flex-col">
                  {/* Message Header */}
                  <div className="p-6 border-b border-gray-200 dark:border-gray-700">
                    <div className="flex items-start justify-between gap-4 mb-4">
                      <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                        {selectedMessage.subject}
                      </h2>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => toggleStar(selectedMessage.id)}
                          className={`p-2 rounded-lg transition-colors ${
                            starredMessages.has(selectedMessage.id)
                              ? "text-yellow-500 bg-yellow-50 dark:bg-yellow-900/20"
                              : "text-gray-400 hover:text-yellow-500 hover:bg-gray-100 dark:hover:bg-gray-700"
                          }`}
                        >
                          <Star className={`w-5 h-5 ${starredMessages.has(selectedMessage.id) ? "fill-current" : ""}`} />
                        </button>
                        <button className="p-2 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                          <Archive className="w-5 h-5" />
                        </button>
                        <button className="p-2 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors">
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="relative w-12 h-12 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700 flex-shrink-0">
                        {selectedMessage.senderAvatar ? (
                          <Image
                            src={selectedMessage.senderAvatar}
                            alt={selectedMessage.senderName}
                            fill
                            className="object-cover"
                            unoptimized
                          />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center">
                            <User className="w-6 h-6 text-gray-500" />
                          </div>
                        )}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p className="font-semibold text-gray-900 dark:text-white">
                            {selectedMessage.senderName}
                          </p>
                          <span className={`px-2 py-0.5 rounded text-xs font-medium ${getRoleBadgeColor(selectedMessage.senderRole)}`}>
                            {selectedMessage.senderRole}
                          </span>
                        </div>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          {new Date(selectedMessage.timestamp).toLocaleDateString("en-GB", {
                            weekday: "long",
                            day: "numeric",
                            month: "long",
                            year: "numeric",
                            hour: "numeric",
                            minute: "2-digit",
                          })}
                        </p>
                        {selectedMessage.childName && (
                          <p className="text-sm text-blue-600 dark:text-blue-400 mt-1">
                            Regarding: {selectedMessage.childName}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Message Body */}
                  <div className="flex-1 overflow-y-auto p-6">
                    <div className="prose prose-sm dark:prose-invert max-w-none">
                      {selectedMessage.content.split("\n").map((line, idx) => (
                        <p key={idx} className="mb-2 text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                          {line || <br />}
                        </p>
                      ))}
                    </div>
                  </div>

                  {/* Reply Actions */}
                  <div className="p-4 border-t border-gray-200 dark:border-gray-700">
                    <div className="flex gap-2">
                      <Button variant="primary" className="flex-1">
                        <Send className="w-4 h-4 mr-2" />
                        Reply
                      </Button>
                      <Button variant="ghost">
                        <Paperclip className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center p-8">
                  <div className="p-4 rounded-full bg-gray-100 dark:bg-gray-700 mb-4">
                    <MessageSquare className="w-12 h-12 text-gray-400 dark:text-gray-500" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    Select a message
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center max-w-xs">
                    Choose a message from the list to view its contents
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
