/**
 * Document template library — comprehensive set of professional templates.
 * Each template includes realistic, original content ready for editing.
 */

export interface DocTemplate {
  id: string;
  label: string;
  category: string;
  title: string;
  html: string;
}

export const DOC_TEMPLATES: DocTemplate[] = [
  // ═══════════════════════════════════════════════
  // RESUMES & CVs
  // ═══════════════════════════════════════════════
  { id: "resume-modern", label: "Modern Resume", category: "Resumes",
    title: "Resume — Amina Okafor",
    html: '<h1 style="font-size:28px;font-weight:bold;margin-bottom:4px;">Amina Okafor</h1><p style="color:#6b7280;margin-bottom:16px;">amina.okafor@email.com · +234 801 234 5678 · Lagos, Nigeria</p><h2>Professional Summary</h2><p>Results-driven software engineer with 5+ years of experience building scalable web applications. Passionate about clean code and mentoring junior developers.</p><h2>Experience</h2><h3>Senior Frontend Developer — Andela</h3><p style="color:#6b7280;font-size:12px;">Mar 2022 – Present</p><ul><li>Led the migration of a legacy app to React, reducing load time by 40%</li><li>Managed a cross-functional team of 8 engineers</li><li>Implemented CI/CD pipelines cutting deployment time from 2 hours to 15 minutes</li></ul><h3>Frontend Developer — Paystack</h3><p style="color:#6b7280;font-size:12px;">Jan 2020 – Feb 2022</p><ul><li>Built the merchant dashboard used by 60,000+ businesses</li><li>Reduced customer support tickets by 30% through improved UX</li></ul><h2>Education</h2><h3>B.Sc. Computer Science — University of Lagos</h3><p style="color:#6b7280;font-size:12px;">Graduated 2019 · First Class Honours</p><h2>Skills</h2><p>React · TypeScript · Node.js · Python · PostgreSQL · AWS · Figma · Git</p>' },

  { id: "resume-executive", label: "Executive Resume", category: "Resumes",
    title: "Executive Resume",
    html: '<h1 style="font-size:26px;font-weight:bold;text-align:center;letter-spacing:1px;">JOHN KOFFI MENSAH</h1><p style="text-align:center;color:#6b7280;font-size:13px;">Chief Operations Officer · Strategic Leader · MBA</p><p style="text-align:center;color:#6b7280;font-size:12px;">Accra, Ghana · john.mensah@email.com · +233 20 555 1234</p><hr style="margin:16px 0;"/><h2>Executive Profile</h2><p>Accomplished C-suite executive with 15+ years driving operational excellence, digital transformation, and revenue growth across West Africa. Proven track record of building high-performing teams and delivering $50M+ in cost savings through process optimization.</p><h2>Leadership Experience</h2><h3>Chief Operations Officer — Pan-African Holdings Group</h3><p style="color:#6b7280;font-size:12px;">2020 – Present · Accra, Ghana</p><ul><li>Oversee operations across 6 countries with 2,400+ employees</li><li>Delivered ₵45M in annual cost savings through supply chain restructuring</li><li>Led digital transformation initiative resulting in 60% process automation</li></ul><h3>VP Operations — Stanbic Investment Corp</h3><p style="color:#6b7280;font-size:12px;">2015 – 2020 · Lagos, Nigeria</p><ul><li>Managed $120M annual operating budget</li><li>Grew regional revenue by 35% through market expansion strategy</li></ul><h2>Education</h2><p><strong>MBA, Strategy & Operations</strong> — London Business School, 2015</p><p><strong>B.Sc. Industrial Engineering</strong> — Kwame Nkrumah University, 2010</p><h2>Board Positions</h2><ul><li>Non-Executive Director, Ghana Fintech Association (2022–Present)</li><li>Advisory Board Member, West Africa Business Council</li></ul>' },

  { id: "resume-creative", label: "Creative Resume", category: "Resumes",
    title: "Creative Portfolio Resume",
    html: '<div style="border-left:4px solid #8b5cf6;padding-left:16px;"><h1 style="color:#8b5cf6;font-size:28px;">Zara Nkemdirim</h1><p style="color:#6b7280;">UX Designer · Visual Storyteller · Brand Architect</p></div><h2>About</h2><p>Award-winning designer with a passion for creating human-centered digital experiences. My work spans brand identity, product design, and interactive media for clients across Africa and Europe.</p><h2>Selected Work</h2><h3>Lead Product Designer — Flutterwave</h3><p style="color:#6b7280;font-size:12px;">2023 – Present</p><ul><li>Redesigned the payment checkout flow, improving conversion by 28%</li><li>Established the company\'s first design system with 200+ components</li></ul><h3>Senior Designer — DDB Lagos</h3><p style="color:#6b7280;font-size:12px;">2020 – 2023</p><ul><li>Led creative direction for 12 national brand campaigns</li><li>Won 3 Loerie Awards for digital campaign excellence</li></ul><h2>Education</h2><p>B.FA Visual Communication — University of Cape Town, 2019</p><h2>Tools & Skills</h2><p>Figma · Framer · Adobe CC · After Effects · Webflow · Design Thinking · User Research</p>' },

  { id: "cv-academic", label: "Academic CV", category: "Resumes",
    title: "Academic Curriculum Vitae",
    html: '<h1 style="font-size:24px;text-align:center;">Dr. Oluwaseun Adeyinka</h1><p style="text-align:center;color:#6b7280;">Department of Biochemistry · University of Ibadan · Nigeria</p><p style="text-align:center;color:#6b7280;font-size:12px;">o.adeyinka@ui.edu.ng · ORCID: 0000-0002-XXXX-XXXX</p><h2>Research Interests</h2><p>Molecular biology, protein engineering, drug discovery for tropical diseases, computational biochemistry</p><h2>Academic Appointments</h2><p><strong>Associate Professor</strong> — University of Ibadan (2021–Present)</p><p><strong>Lecturer I</strong> — University of Ibadan (2016–2021)</p><p><strong>Postdoctoral Fellow</strong> — University of Oxford (2014–2016)</p><h2>Education</h2><p><strong>Ph.D. Biochemistry</strong> — University of Cambridge, 2014</p><p><strong>M.Sc. Molecular Biology</strong> — University of Lagos, 2010</p><p><strong>B.Sc. Biochemistry</strong> — University of Ibadan, 2008 (First Class)</p><h2>Selected Publications</h2><ul><li>Adeyinka, O. et al. (2024). "Novel protein targets for antimalarial drug development." <em>Nature Chemistry</em>, 16(3), 245–258.</li><li>Adeyinka, O. & Smith, J. (2022). "Computational approaches to enzyme engineering." <em>Journal of Molecular Biology</em>, 434(12), 167–182.</li></ul><h2>Grants & Funding</h2><ul><li>Wellcome Trust Research Grant — £350,000 (2023–2026)</li><li>African Academy of Sciences Fellowship — $50,000 (2022)</li></ul>' },

  // ═══════════════════════════════════════════════
  // LETTERS
  // ═══════════════════════════════════════════════
  { id: "letter-business", label: "Business Letter", category: "Letters",
    title: "Business Letter",
    html: '<p style="text-align:right;">Educo International School<br/>45 Victoria Island, Lagos<br/>March 16, 2026</p><p>Mrs. Ngozi Okonkwo<br/>Director of Education<br/>Federal Ministry of Education<br/>Abuja, Nigeria</p><p>Dear Mrs. Okonkwo,</p><p>I am writing to formally request approval for the integration of our new digital learning platform across the school network. The platform has been tested extensively and has shown a 35% improvement in student engagement metrics.</p><p>Attached is the full proposal with implementation timelines and budget projections. We are confident this initiative aligns with the Ministry\'s 2026 education modernization goals.</p><p>Please do not hesitate to contact me should you require further information.</p><p>Sincerely,<br/><strong>Dr. Emmanuel Adeyemi</strong><br/>Principal, Educo International School</p>' },

  { id: "letter-cover", label: "Cover Letter", category: "Letters",
    title: "Job Application Cover Letter",
    html: '<p style="text-align:right;">12 Admiralty Way<br/>Lekki Phase 1, Lagos<br/>March 16, 2026</p><p>Human Resources Department<br/>Interswitch Group<br/>Lagos, Nigeria</p><p>Dear Hiring Manager,</p><p>I am writing to express my interest in the Senior Software Engineer position advertised on your careers page. With five years of experience in fintech development and a strong background in distributed systems, I am confident I would be a valuable addition to your team.</p><p>In my current role at Paystack, I have led the development of payment processing systems handling over 500,000 daily transactions. I designed and implemented a microservices architecture that reduced system downtime by 99.2% and improved transaction processing speed by 45%.</p><p>What excites me most about Interswitch is your commitment to driving financial inclusion across Africa. I am particularly drawn to your work on the Verve card platform and would welcome the opportunity to contribute to its evolution.</p><p>I have attached my resume for your review and would be delighted to discuss how my experience aligns with your team\'s goals.</p><p>Thank you for your consideration.</p><p>Warm regards,<br/><strong>Chidinma Eze</strong><br/>chidinma.eze@email.com · +234 803 456 7890</p>' },

  { id: "letter-recommendation", label: "Recommendation Letter", category: "Letters",
    title: "Letter of Recommendation",
    html: '<p style="text-align:right;">Educo International School<br/>Lagos, Nigeria<br/>March 16, 2026</p><p>To Whom It May Concern,</p><p>It is with great pleasure that I write this letter of recommendation for <strong>Oluwafemi Bankole</strong>, who has been a student at Educo International School for the past six years.</p><p>Oluwafemi consistently ranks among the top 5% of his class and has demonstrated exceptional abilities in mathematics and the sciences. He achieved an A1 in all nine subjects in his WAEC examination and scored 340 in his JAMB UTME.</p><p>Beyond academics, Oluwafemi serves as the President of the Science Club and has led the school\'s team to victory at the National Science Olympiad for two consecutive years. He is a natural leader who inspires his peers through dedication and intellectual curiosity.</p><p>His character is equally impressive. He volunteers weekly at the school\'s community outreach program and has mentored junior students in mathematics for the past two years.</p><p>I recommend Oluwafemi without reservation. He will be an asset to any university program he joins.</p><p>Sincerely,<br/><strong>Dr. Emmanuel Adeyemi</strong><br/>Principal, Educo International School<br/>e.adeyemi@educo.ng · +234 801 555 0001</p>' },

  { id: "letter-resignation", label: "Resignation Letter", category: "Letters",
    title: "Letter of Resignation",
    html: '<p style="text-align:right;">March 16, 2026</p><p>Mrs. Grace Okafor<br/>Head of Department, Mathematics<br/>Educo International School<br/>Lagos, Nigeria</p><p>Dear Mrs. Okafor,</p><p>I am writing to formally notify you of my resignation from my position as Mathematics Teacher at Educo International School, effective April 15, 2026. This provides the standard 30-day notice period as stipulated in my contract.</p><p>I have accepted a position as Head of Mathematics at another institution, an opportunity that aligns with my long-term career goals. This was not an easy decision — my four years at Educo have been incredibly rewarding.</p><p>During the transition period, I am committed to:</p><ul><li>Completing all current term assessments and grading</li><li>Preparing comprehensive handover notes for my successor</li><li>Training any interim replacement on the curriculum structure</li></ul><p>I am deeply grateful for the mentorship, professional development, and friendships I have gained here. Educo will always hold a special place in my career journey.</p><p>Thank you for your understanding and support.</p><p>Respectfully,<br/><strong>Tunde Afolabi</strong></p>' },

  // ═══════════════════════════════════════════════
  // LEGAL & AGREEMENTS
  // ═══════════════════════════════════════════════
  { id: "consultant-agreement", label: "Consultant Agreement", category: "Legal",
    title: "Consultant Agreement",
    html: '<h1>Consultant Agreement</h1><p style="color:#6b7280;">Effective Date: ____________</p><p>This Consultant Agreement ("Agreement") is entered into by and between:</p><p><strong>Client:</strong> Educo International School<br/><strong>Consultant:</strong> ____________</p><h2>1. Services</h2><p>The Consultant agrees to provide the following services:</p><ul><li>Curriculum development and review</li><li>Teacher training workshops (minimum 4 sessions per term)</li><li>Educational technology integration advisory</li><li>Monthly progress reports and recommendations</li></ul><h2>2. Term</h2><p>This Agreement shall commence on ____________ and continue until ____________, unless terminated earlier.</p><h2>3. Termination</h2><p>Either Party may terminate with <strong>thirty (30) days</strong> written notice. Upon termination, the Consultant shall be compensated for all services rendered.</p><h2>4. Compensation</h2><ul><li><strong>Rate:</strong> ₦____________ per month</li><li><strong>Payment Schedule:</strong> Net 15 days from invoice</li><li><strong>Expenses:</strong> Pre-approved expenses reimbursed within 30 days</li></ul><h2>5. Confidentiality</h2><p>The Consultant agrees to maintain strict confidentiality of all proprietary information.</p><h2>6. Governing Law</h2><p>This Agreement shall be governed by the laws of the Federal Republic of Nigeria.</p><p style="margin-top:32px;"><strong>CLIENT:</strong> Signature: ________________________ Date: ____________</p><p><strong>CONSULTANT:</strong> Signature: ________________________ Date: ____________</p>' },

  { id: "nda", label: "Non-Disclosure Agreement", category: "Legal",
    title: "Non-Disclosure Agreement",
    html: '<h1>Non-Disclosure Agreement</h1><p style="color:#6b7280;">Date: ____________</p><p>Between <strong>Educo International School</strong> ("Disclosing Party") and <strong>____________</strong> ("Receiving Party").</p><h2>1. Confidential Information</h2><p>Includes but is not limited to: student records, financial data, proprietary curriculum, technology systems, and business strategies.</p><h2>2. Obligations</h2><ul><li>Maintain strict confidentiality</li><li>Not disclose to third parties without written consent</li><li>Use information solely for the stated purpose</li><li>Return or destroy all materials upon termination</li></ul><h2>3. Duration</h2><p>This Agreement remains in effect for <strong>three (3) years</strong>.</p><h2>4. Governing Law</h2><p>Governed by the laws of Nigeria.</p><p style="margin-top:24px;"><strong>DISCLOSING PARTY:</strong> ________________________ Date: ____________</p><p><strong>RECEIVING PARTY:</strong> ________________________ Date: ____________</p>' },

  { id: "employment-contract", label: "Employment Contract", category: "Legal",
    title: "Employment Contract",
    html: '<h1>Employment Contract</h1><p style="color:#6b7280;">Date: ____________</p><p>This Employment Contract is between <strong>Educo International School</strong> ("Employer") and <strong>____________</strong> ("Employee").</p><h2>1. Position & Duties</h2><p><strong>Title:</strong> ____________<br/><strong>Department:</strong> ____________<br/><strong>Reports to:</strong> ____________</p><p>The Employee shall perform all duties reasonably associated with the above position.</p><h2>2. Compensation</h2><ul><li><strong>Base Salary:</strong> ₦____________ per annum, paid monthly</li><li><strong>Benefits:</strong> Health insurance, pension contribution (8%), annual leave (21 days)</li><li><strong>Probation:</strong> 3 months from start date</li></ul><h2>3. Working Hours</h2><p>Monday to Friday, 7:00 AM to 4:00 PM. Occasional weekend duties as required.</p><h2>4. Termination</h2><p>Either party may terminate with 30 days written notice. Gross misconduct may result in immediate termination.</p><h2>5. Confidentiality</h2><p>The Employee agrees to keep all institutional information confidential during and after employment.</p><h2>6. Governing Law</h2><p>This contract is governed by Nigerian Labour Law.</p><p style="margin-top:24px;"><strong>EMPLOYER:</strong> ________________________ Date: ____________</p><p><strong>EMPLOYEE:</strong> ________________________ Date: ____________</p>' },

  { id: "mou", label: "Memorandum of Understanding", category: "Legal",
    title: "Memorandum of Understanding",
    html: '<h1>Memorandum of Understanding</h1><p style="color:#6b7280;">Effective Date: ____________</p><p>This MOU is entered into between:</p><p><strong>Party A:</strong> Educo International School<br/><strong>Party B:</strong> ____________</p><h2>1. Purpose</h2><p>The Parties wish to establish a framework for collaboration in ____________.</p><h2>2. Scope of Collaboration</h2><ul><li>Joint program development and delivery</li><li>Resource sharing and facility access</li><li>Staff exchange and professional development</li><li>Joint research initiatives</li></ul><h2>3. Responsibilities</h2><p><strong>Party A shall:</strong> ____________</p><p><strong>Party B shall:</strong> ____________</p><h2>4. Duration</h2><p>This MOU is effective for <strong>two (2) years</strong> and may be renewed by mutual agreement.</p><h2>5. Financial Arrangements</h2><p>Each party bears its own costs unless otherwise agreed in writing.</p><h2>6. Termination</h2><p>Either party may withdraw with 60 days written notice.</p><p style="margin-top:24px;"><strong>PARTY A:</strong> ________________________ Date: ____________</p><p><strong>PARTY B:</strong> ________________________ Date: ____________</p>' },

  // ═══════════════════════════════════════════════
  // BUSINESS & WORK
  // ═══════════════════════════════════════════════
  { id: "meeting-notes", label: "Meeting Notes", category: "Business",
    title: "Staff Meeting Notes — March 2026",
    html: '<h2>Staff Meeting Notes</h2><p><strong>Date:</strong> March 16, 2026 · 10:00 AM</p><p><strong>Attendees:</strong> Dr. Adeyemi, Mrs. Obi, Mr. Chukwu, Ms. Bello</p><h3>Agenda</h3><ul><li>Review Q1 academic performance</li><li>Parent-teacher conference planning</li><li>Science lab equipment budget</li></ul><h3>Discussion</h3><ul><li>Q1 results: 12% improvement in maths scores</li><li>Conference scheduled April 5 — need 15 volunteers</li><li>Lab budget approved: ₦2.5M</li></ul><h3>Action Items</h3><ul><li><strong>Mrs. Obi</strong> — Send invitations by March 22</li><li><strong>Mr. Chukwu</strong> — Submit equipment order by March 20</li><li><strong>Ms. Bello</strong> — Prepare performance dashboards</li></ul>' },

  { id: "proposal", label: "Project Proposal", category: "Business",
    title: "Digital Library Proposal",
    html: '<h1>Project Proposal: Digital Library Initiative</h1><p style="color:#6b7280;">Prepared by Academic Innovation Committee · March 2026</p><h2>Executive Summary</h2><p>Plan to digitize the school library and provide 24/7 access to 10,000+ educational resources.</p><h2>Objectives</h2><ul><li>Digitize 80% of physical catalog within 6 months</li><li>Provide offline access for low-connectivity areas</li><li>Reduce textbook costs by 40%</li></ul><h2>Timeline</h2><p><strong>Phase 1 (Apr–May):</strong> Development and digitization</p><p><strong>Phase 2 (Jun–Jul):</strong> Pilot with SS1/SS2</p><p><strong>Phase 3 (Aug–Sep):</strong> Full deployment</p><h2>Budget</h2><p>Total: <strong>₦4,800,000</strong></p><ul><li>Platform: ₦2,000,000</li><li>Content licensing: ₦1,500,000</li><li>Hardware: ₦1,300,000</li></ul>' },

  { id: "newsletter", label: "Newsletter", category: "Business",
    title: "Monthly Newsletter — March 2026",
    html: '<div style="text-align:center;padding:16px;background:#eff6ff;border-radius:8px;margin-bottom:16px;"><h1 style="color:#2563eb;margin:0;">Educo Monthly</h1><p style="color:#6b7280;margin:4px 0 0;">Edition 14 · March 2026</p></div><h2>Academic Highlights</h2><ul><li>95% pass rate in mock exams</li><li>3 students qualified for National Science Olympiad</li><li>New coding club launched with 40 members</li></ul><h2>Upcoming Events</h2><p><strong>April 5:</strong> Parent-Teacher Conference</p><p><strong>April 12:</strong> Inter-house Sports Day</p><h2>Staff Spotlight</h2><p>Congratulations to <strong>Mr. Tunde Adebayo</strong> — Teacher of the Term!</p>' },

  { id: "business-plan", label: "Business Plan", category: "Business",
    title: "Business Plan — EdTech Startup",
    html: '<h1>Business Plan</h1><p style="color:#6b7280;">EduConnect Africa · March 2026</p><h2>Executive Summary</h2><p>EduConnect Africa is a mobile-first learning platform connecting students across West Africa with qualified tutors for personalized, affordable education.</p><h2>Problem</h2><p>70% of secondary school students in Nigeria lack access to quality supplementary education. Private tutoring costs ₦50,000+ per month, putting it out of reach for most families.</p><h2>Solution</h2><p>An AI-powered platform that matches students with vetted tutors for live video sessions at ₦2,000 per hour, with offline content access.</p><h2>Market Size</h2><ul><li>Total addressable market: $4.2B (West Africa EdTech)</li><li>Target: 500,000 students in Year 1</li><li>Revenue target: ₦2.4B by Year 3</li></ul><h2>Revenue Model</h2><ul><li>Commission: 20% per tutoring session</li><li>Premium subscriptions: ₦5,000/month</li><li>Institutional partnerships: B2B licensing</li></ul><h2>Team</h2><p><strong>CEO:</strong> ____________ (10 years EdTech experience)</p><p><strong>CTO:</strong> ____________ (Ex-Andela engineer)</p><p><strong>COO:</strong> ____________ (Operations at Jumia)</p>' },

  { id: "invoice", label: "Invoice", category: "Business",
    title: "Invoice #INV-2026-001",
    html: '<div style="display:flex;justify-content:space-between;align-items:flex-start;"><div><h1 style="color:#2563eb;margin:0;">INVOICE</h1><p style="color:#6b7280;">#INV-2026-001</p></div><div style="text-align:right;"><p><strong>Educo International School</strong><br/>45 Victoria Island, Lagos<br/>admin@educo.ng</p></div></div><hr style="margin:16px 0;"/><p><strong>Bill To:</strong><br/>____________<br/>____________</p><p><strong>Invoice Date:</strong> March 16, 2026<br/><strong>Due Date:</strong> March 31, 2026</p><h2>Services</h2><p><strong>1. Curriculum Consultation</strong> — 20 hours × ₦25,000 = <strong>₦500,000</strong></p><p><strong>2. Teacher Training Workshop</strong> — 2 sessions × ₦150,000 = <strong>₦300,000</strong></p><p><strong>3. Assessment Design</strong> — Lump sum = <strong>₦200,000</strong></p><hr/><p style="text-align:right;font-size:18px;"><strong>Total: ₦1,000,000</strong></p><p style="color:#6b7280;font-size:12px;">Payment: Bank transfer to Educo International School · GTBank · Account: 0123456789</p>' },

  { id: "sop", label: "Standard Operating Procedure", category: "Business",
    title: "SOP — Student Admission Process",
    html: '<h1>Standard Operating Procedure</h1><p><strong>Title:</strong> Student Admission Process<br/><strong>Department:</strong> Admissions<br/><strong>Version:</strong> 2.0 · Effective March 2026</p><h2>1. Purpose</h2><p>To establish a standardized process for admitting new students to ensure fairness, efficiency, and compliance.</p><h2>2. Scope</h2><p>Applies to all new student admissions for Primary, Junior Secondary, and Senior Secondary levels.</p><h2>3. Procedure</h2><h3>Step 1: Application Receipt</h3><ul><li>Parent/guardian completes online application form</li><li>Required documents: birth certificate, previous school reports, passport photos</li><li>Application fee: ₦10,000 (non-refundable)</li></ul><h3>Step 2: Entrance Assessment</h3><ul><li>Scheduled within 5 business days of application</li><li>Subjects: English, Mathematics, General Knowledge</li><li>Duration: 2 hours</li></ul><h3>Step 3: Interview</h3><ul><li>Student interview with Head of Department</li><li>Parent meeting with Admissions Officer</li></ul><h3>Step 4: Decision & Communication</h3><ul><li>Results communicated within 7 business days</li><li>Acceptance letter sent via email with fee schedule</li></ul><h2>4. Responsible Parties</h2><p><strong>Admissions Officer:</strong> Initial review<br/><strong>HOD:</strong> Assessment oversight<br/><strong>Principal:</strong> Final approval</p>' },

  // ═══════════════════════════════════════════════
  // EDUCATION
  // ═══════════════════════════════════════════════
  { id: "lesson-plan", label: "Lesson Plan", category: "Education",
    title: "Lesson Plan — Mathematics JS2",
    html: '<h1>Lesson Plan</h1><p><strong>Subject:</strong> Mathematics<br/><strong>Class:</strong> JS2 · <strong>Term:</strong> 2<br/><strong>Topic:</strong> Introduction to Algebra<br/><strong>Duration:</strong> 80 minutes (double period)<br/><strong>Teacher:</strong> Mr. Afolabi</p><h2>Learning Objectives</h2><p>By the end of this lesson, students should be able to:</p><ul><li>Define variables, constants, and algebraic expressions</li><li>Simplify basic algebraic expressions</li><li>Solve simple linear equations with one unknown</li></ul><h2>Materials Needed</h2><ul><li>Whiteboard and markers</li><li>Student worksheets (printed)</li><li>Calculator (optional)</li></ul><h2>Lesson Structure</h2><h3>Introduction (15 min)</h3><p>Review of arithmetic operations. Introduce the concept of "unknown" values using real-life examples (e.g., "I have some oranges...").</p><h3>Development (40 min)</h3><ul><li>Define key terms: variable, coefficient, constant, expression</li><li>Worked examples: Simplify 3x + 2x, 5y - 2y + 4</li><li>Guided practice: Students solve 5 problems on worksheets</li></ul><h3>Activity (15 min)</h3><p>Pair work: Create and solve each other\'s equations.</p><h3>Closure (10 min)</h3><p>Class discussion, key takeaways, assign homework.</p><h2>Homework</h2><p>Textbook page 84, exercises 1–15 (due next class).</p><h2>Assessment</h2><p>Formative: Class participation and worksheet accuracy. Summative: End-of-topic test (Week 6).</p>' },

  { id: "class-notes", label: "Class Notes", category: "Education",
    title: "Class Notes — Biology SS2",
    html: '<h1>Biology — SS2 · Week 8</h1><p style="color:#6b7280;">Topic: Ecology and Ecosystems · Mrs. Adebayo</p><h2>Learning Objectives</h2><ul><li>Define ecosystem and identify its components</li><li>Distinguish between biotic and abiotic factors</li><li>Explain energy flow through food chains</li></ul><h2>Key Concepts</h2><h3>What is an Ecosystem?</h3><p>A community of living organisms interacting with their physical environment. Examples: rainforests, savannas, lakes.</p><h3>Energy Flow</h3><p>Producers → Primary consumers → Secondary consumers → Tertiary consumers → Decomposers</p><p>Only about <strong>10%</strong> of energy transfers between trophic levels.</p><h2>Homework</h2><ul><li>Read Chapter 12, pages 180–195</li><li>Draw a savanna ecosystem food web</li></ul>' },

  { id: "essay", label: "Essay Template", category: "Education",
    title: "Academic Essay",
    html: '<h1>The Impact of Technology on Education in Africa</h1><p style="color:#6b7280;">By Chinelo Eze · SS3 · March 2026</p><h2>Introduction</h2><p>Technology has transformed every aspect of modern life, and education is no exception. This essay examines the positive impact of technology on education in Africa while acknowledging remaining challenges.</p><h2>Access to Knowledge</h2><p>Platforms like Khan Academy and uLesson have made quality content accessible to millions, regardless of location. A student in rural Kano can access the same lessons as one in Lagos or London.</p><h2>Interactive Learning</h2><p>Virtual labs, educational games, and multimedia presentations help students understand complex concepts. Research shows students using digital tools scored 23% higher in STEM subjects.</p><h2>Challenges</h2><p>The digital divide, unreliable electricity, high data costs, and shortage of trained teachers remain obstacles.</p><h2>Conclusion</h2><p>Technology holds immense promise for African education. With continued investment in infrastructure and training, it can become the great equalizer.</p>' },

  { id: "report-card-template", label: "Report Card", category: "Education",
    title: "Student Report Card Template",
    html: '<div style="text-align:center;border:2px solid #2563eb;padding:16px;border-radius:8px;margin-bottom:16px;"><h1 style="color:#2563eb;margin:0;">EDUCO INTERNATIONAL SCHOOL</h1><p style="margin:4px 0;">Student Academic Report Card</p><p style="color:#6b7280;font-size:12px;">Academic Year: 2025/2026 · Term: ___</p></div><p><strong>Student Name:</strong> ____________ <strong>Class:</strong> ____________</p><p><strong>Admission No:</strong> ____________ <strong>Age:</strong> ____________</p><h2>Academic Performance</h2><p><strong>Mathematics:</strong> ___/100 · Grade: ___ · Remark: ____________</p><p><strong>English Language:</strong> ___/100 · Grade: ___ · Remark: ____________</p><p><strong>Science:</strong> ___/100 · Grade: ___ · Remark: ____________</p><p><strong>Social Studies:</strong> ___/100 · Grade: ___ · Remark: ____________</p><p><strong>French:</strong> ___/100 · Grade: ___ · Remark: ____________</p><h2>Summary</h2><p><strong>Total Score:</strong> ___/500 · <strong>Average:</strong> ___% · <strong>Position:</strong> ___ of ___</p><h2>Comments</h2><p><strong>Class Teacher:</strong> ____________</p><p><strong>Principal:</strong> ____________</p><p><strong>Next Term Begins:</strong> ____________</p>' },

  { id: "research-paper", label: "Research Paper", category: "Education",
    title: "Research Paper Template",
    html: '<h1 style="text-align:center;">Title of Research Paper</h1><p style="text-align:center;color:#6b7280;">Author Name(s)<br/>Institution · Department<br/>Email: ____________</p><h2>Abstract</h2><p>Provide a concise summary of 150–250 words covering the research question, methodology, key findings, and conclusions.</p><h2>1. Introduction</h2><p>Present the background, research gap, and objectives of the study.</p><h2>2. Literature Review</h2><p>Survey existing research and theoretical frameworks relevant to the topic.</p><h2>3. Methodology</h2><p>Describe the research design, data collection methods, sample size, and analytical tools used.</p><h2>4. Results</h2><p>Present findings using tables, figures, and statistical analysis.</p><h2>5. Discussion</h2><p>Interpret results in the context of existing literature. Address limitations.</p><h2>6. Conclusion</h2><p>Summarize key findings and suggest directions for future research.</p><h2>References</h2><p>[List references in APA/MLA/Chicago format]</p>' },

  // ═══════════════════════════════════════════════
  // PLANNING & MANAGEMENT
  // ═══════════════════════════════════════════════
  { id: "project-plan", label: "Project Plan", category: "Planning",
    title: "Project Implementation Plan",
    html: '<h1>Project Implementation Plan</h1><p style="color:#6b7280;">Project: School Management System Upgrade<br/>Project Manager: ____________ · Start Date: April 2026</p><h2>1. Project Overview</h2><p>Upgrade the school\'s administrative systems from paper-based to fully digital, covering student records, attendance, grading, and communication.</p><h2>2. Objectives</h2><ul><li>Digitize all student records by end of Term 2</li><li>Implement automated attendance tracking</li><li>Launch parent communication portal</li><li>Train 100% of staff on new systems</li></ul><h2>3. Timeline</h2><p><strong>Phase 1 — Setup (Weeks 1–2):</strong> Infrastructure, accounts, data migration</p><p><strong>Phase 2 — Pilot (Weeks 3–4):</strong> Test with 2 classes, gather feedback</p><p><strong>Phase 3 — Rollout (Weeks 5–8):</strong> School-wide deployment</p><p><strong>Phase 4 — Review (Week 9–10):</strong> Performance analysis, optimization</p><h2>4. Resources Required</h2><ul><li>Budget: ₦3,500,000</li><li>Personnel: 2 IT staff, 1 project coordinator</li><li>Equipment: 10 tablets for teachers, 2 servers</li></ul><h2>5. Risk Management</h2><ul><li><strong>Risk:</strong> Staff resistance to change → <strong>Mitigation:</strong> Early training, champions program</li><li><strong>Risk:</strong> Internet downtime → <strong>Mitigation:</strong> Offline-capable system</li></ul>' },

  { id: "event-plan", label: "Event Plan", category: "Planning",
    title: "Annual Sports Day Plan",
    html: '<h1>Event Plan: Annual Inter-House Sports Day</h1><p style="color:#6b7280;">Date: April 12, 2026 · Venue: School Sports Complex</p><h2>Event Overview</h2><p>The annual Inter-House Sports Day brings together all students, staff, and parents for a day of athletic competition, team spirit, and community celebration.</p><h2>Schedule</h2><p><strong>7:00 AM</strong> — Setup and preparation</p><p><strong>8:00 AM</strong> — Opening ceremony and march past</p><p><strong>8:30 AM</strong> — Track events begin (100m, 200m, 400m, relay)</p><p><strong>10:30 AM</strong> — Break (refreshments served)</p><p><strong>11:00 AM</strong> — Field events (long jump, high jump, shot put)</p><p><strong>1:00 PM</strong> — Lunch break</p><p><strong>2:00 PM</strong> — Finals and special events</p><p><strong>3:30 PM</strong> — Award ceremony and closing</p><h2>Houses</h2><ul><li>Red House (Eagles)</li><li>Blue House (Dolphins)</li><li>Green House (Panthers)</li><li>Yellow House (Lions)</li></ul><h2>Committee</h2><p><strong>Chairman:</strong> Mr. Okoye (PE Department)</p><p><strong>Logistics:</strong> Mrs. Bello</p><p><strong>Medical:</strong> School Nurse + St. John Ambulance</p><h2>Budget</h2><p>Total: ₦850,000 (trophies, refreshments, equipment, first aid)</p>' },

  { id: "budget-template", label: "Budget Template", category: "Planning",
    title: "Annual Department Budget",
    html: '<h1>Annual Budget Proposal</h1><p><strong>Department:</strong> Science Department<br/><strong>Academic Year:</strong> 2026/2027<br/><strong>Prepared by:</strong> Dr. Chukwu, HOD Science</p><h2>Budget Summary</h2><p><strong>Total Requested:</strong> ₦4,250,000</p><h2>1. Laboratory Equipment — ₦1,800,000</h2><ul><li>Microscopes (10 units): ₦500,000</li><li>Chemistry reagents and supplies: ₦400,000</li><li>Physics apparatus: ₦350,000</li><li>Biology specimens and models: ₦300,000</li><li>Safety equipment (goggles, gloves, extinguishers): ₦250,000</li></ul><h2>2. Teaching Materials — ₦850,000</h2><ul><li>Textbooks and reference materials: ₦400,000</li><li>Digital resources and software licenses: ₦250,000</li><li>Charts, models, and visual aids: ₦200,000</li></ul><h2>3. Professional Development — ₦600,000</h2><ul><li>STEM workshop attendance (4 teachers): ₦400,000</li><li>Online certification courses: ₦200,000</li></ul><h2>4. Student Activities — ₦500,000</h2><ul><li>Science Olympiad preparation: ₦200,000</li><li>Field trips (2 per term): ₦300,000</li></ul><h2>5. Maintenance — ₦500,000</h2><ul><li>Lab equipment repairs: ₦300,000</li><li>Furniture replacement: ₦200,000</li></ul>' },

  // ═══════════════════════════════════════════════
  // REPORTS
  // ═══════════════════════════════════════════════
  { id: "academic-report", label: "Academic Report", category: "Reports",
    title: "Term 1 Academic Performance Report",
    html: '<h1>Academic Performance Report</h1><p><strong>Term:</strong> 1 · 2025/2026<br/><strong>Prepared by:</strong> Academic Affairs Department</p><h2>Key Findings</h2><ul><li>Overall pass rate: 87% (up from 82%)</li><li>Mathematics: +15% average improvement</li><li>English: 92% pass rate (strongest subject)</li><li>Science: Needs intervention in JSS3</li></ul><h2>Recommendations</h2><ul><li>Implement after-school science tutoring</li><li>Recognize top-performing students</li><li>Additional teacher training in differentiated instruction</li></ul><h2>Conclusion</h2><p>Positive growth overall. Target: 90% pass rate by year end.</p>' },

  { id: "incident-report", label: "Incident Report", category: "Reports",
    title: "Incident Report",
    html: '<h1>Incident Report</h1><p style="color:#6b7280;">Report #: IR-2026-___ · Date of Incident: ____________</p><h2>Incident Details</h2><p><strong>Date & Time:</strong> ____________</p><p><strong>Location:</strong> ____________</p><p><strong>Persons Involved:</strong> ____________</p><p><strong>Witnesses:</strong> ____________</p><h2>Description of Incident</h2><p>Provide a detailed, factual account of what occurred:</p><p>____________</p><h2>Immediate Actions Taken</h2><ul><li>____________</li><li>____________</li></ul><h2>Injuries / Damage</h2><p>____________</p><h2>Root Cause Analysis</h2><p>____________</p><h2>Corrective Actions</h2><ul><li>____________</li><li>____________</li></ul><h2>Reported By</h2><p>Name: ____________ · Position: ____________ · Date: ____________</p><p>Signature: ________________________</p>' },

  { id: "annual-report", label: "Annual Report", category: "Reports",
    title: "School Annual Report 2025",
    html: '<div style="text-align:center;padding:24px;background:linear-gradient(135deg,#1e40af,#3b82f6);color:white;border-radius:12px;margin-bottom:20px;"><h1 style="margin:0;color:white;">Annual Report 2025</h1><p style="margin:4px 0 0;opacity:0.8;">Educo International School</p></div><h2>Message from the Principal</h2><p>2025 was a transformative year for Educo. We achieved record academic results, expanded our facilities, and deepened our commitment to holistic education.</p><h2>Academic Achievements</h2><ul><li>92% WAEC pass rate (school record)</li><li>15 students gained university scholarships</li><li>National Science Olympiad champions (2nd consecutive year)</li></ul><h2>Enrollment</h2><p>Total students: 1,245 (up 12% from 2024)<br/>Student-teacher ratio: 18:1</p><h2>Infrastructure</h2><ul><li>New science laboratory complex (₦45M investment)</li><li>Digital library with 5,000+ e-books</li><li>Solar power installation (60% energy independence)</li></ul><h2>Financial Summary</h2><p>Revenue: ₦890M · Expenditure: ₦820M · Surplus: ₦70M</p><h2>Looking Ahead — 2026</h2><ul><li>Launch coding curriculum for all classes</li><li>Expand to 1,500 students</li><li>Begin construction of performing arts center</li></ul>' },

  // ═══════════════════════════════════════════════
  // PERSONAL & MISCELLANEOUS
  // ═══════════════════════════════════════════════
  { id: "personal-journal", label: "Journal Entry", category: "Personal",
    title: "Weekly Reflection Journal",
    html: '<h1>Weekly Reflection</h1><p style="color:#6b7280;">Week of: March 10–16, 2026</p><h2>What went well this week?</h2><p>____________</p><h2>What challenges did I face?</h2><p>____________</p><h2>What did I learn?</h2><p>____________</p><h2>Goals for next week</h2><ul><li>____________</li><li>____________</li><li>____________</li></ul><h2>Gratitude</h2><p>Three things I\'m grateful for this week:</p><ul><li>____________</li><li>____________</li><li>____________</li></ul>' },

  { id: "to-do-list", label: "To-Do List", category: "Personal",
    title: "Weekly To-Do List",
    html: '<h1>Weekly To-Do List</h1><p style="color:#6b7280;">Week of: ____________</p><h2>High Priority</h2><ul><li>☐ ____________</li><li>☐ ____________</li><li>☐ ____________</li></ul><h2>Medium Priority</h2><ul><li>☐ ____________</li><li>☐ ____________</li></ul><h2>Low Priority / Nice to Have</h2><ul><li>☐ ____________</li><li>☐ ____________</li></ul><h2>Notes</h2><p>____________</p>' },

  { id: "recipe", label: "Recipe Card", category: "Personal",
    title: "Recipe — Jollof Rice",
    html: '<h1>Jollof Rice</h1><p style="color:#6b7280;">Prep: 20 min · Cook: 45 min · Serves: 6</p><h2>Ingredients</h2><ul><li>3 cups long grain parboiled rice</li><li>6 medium tomatoes, blended</li><li>3 red bell peppers, blended</li><li>2 scotch bonnet peppers</li><li>2 medium onions (1 blended, 1 diced)</li><li>⅓ cup vegetable oil</li><li>3 tablespoons tomato paste</li><li>2 teaspoons curry powder</li><li>1 teaspoon thyme</li><li>3 bay leaves</li><li>Salt and seasoning cubes to taste</li><li>3 cups chicken stock</li></ul><h2>Instructions</h2><ol><li>Wash rice and soak for 30 minutes, then drain</li><li>Heat oil in a heavy pot. Fry diced onions until golden</li><li>Add tomato paste, fry for 2 minutes</li><li>Add blended tomato-pepper mixture. Cook on medium heat for 25–30 minutes until oil floats on top</li><li>Add spices, seasoning, and stock. Bring to a boil</li><li>Add rice, stir well. Cover tightly with foil then lid</li><li>Cook on low heat for 30–40 minutes until rice is tender</li><li>Fluff with fork and serve</li></ol><p><strong>Serve with:</strong> Fried plantain, coleslaw, grilled chicken</p>' },
];

/** All unique template categories */
export const TEMPLATE_CATEGORIES = [...new Set(DOC_TEMPLATES.map(t => t.category))];

/** Accent colors per category */
export const CATEGORY_COLORS: Record<string, string> = {
  "Resumes": "#3b82f6",
  "Letters": "#22c55e",
  "Legal": "#64748b",
  "Business": "#8b5cf6",
  "Education": "#f59e0b",
  "Planning": "#06b6d4",
  "Reports": "#ec4899",
  "Personal": "#f97316",
};
