/**
 * Presentation slide templates — professional templates organized by category.
 */
import type { SlideData } from "./slide-storage";

export interface SlideTemplate {
  id: string;
  label: string;
  category: string;
  title: string;
  theme: string;
  slides: SlideData[];
}

function s(id: string, content: string, bg = "#ffffff", transition: SlideData["transition"] = "fade"): SlideData {
  return { id, content, notes: "", background: bg, transition };
}

export const SLIDE_TEMPLATES: SlideTemplate[] = [
  // ═══ BUSINESS ═══
  { id: "strategy-consulting", label: "Strategy Consulting", category: "Business", title: "Strategic Consulting Deck", theme: "corporate",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:42px;font-weight:bold;color:#1e3a5f;">Strategic Consulting</h1><p style="font-size:20px;color:#6b7280;margin-top:12px;">Growth Strategy & Market Analysis</p><p style="font-size:14px;color:#9ca3af;margin-top:40px;">Prepared by Educo Consulting Group · March 2026</p></div>', '#f8fafc'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#1e3a5f;border-bottom:3px solid #3b82f6;padding-bottom:8px;">Executive Summary</h2><ul style="font-size:16px;line-height:2;margin-top:20px;color:#374151;"><li>Market opportunity valued at $4.2B with 18% CAGR</li><li>Three strategic pillars: Digital Transformation, Market Expansion, Operational Excellence</li><li>Projected ROI of 340% over 36 months</li><li>Phased implementation with quick wins in Q1</li></ul></div>', '#ffffff'),
      s("s3", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#1e3a5f;border-bottom:3px solid #3b82f6;padding-bottom:8px;">Market Analysis</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:24px;"><div style="background:#eff6ff;padding:20px;border-radius:12px;"><h3 style="font-size:16px;font-weight:bold;color:#2563eb;">Total Addressable Market</h3><p style="font-size:32px;font-weight:bold;color:#1e40af;margin-top:8px;">$4.2B</p></div><div style="background:#f0fdf4;padding:20px;border-radius:12px;"><h3 style="font-size:16px;font-weight:bold;color:#16a34a;">Growth Rate (CAGR)</h3><p style="font-size:32px;font-weight:bold;color:#15803d;margin-top:8px;">18%</p></div><div style="background:#fefce8;padding:20px;border-radius:12px;"><h3 style="font-size:16px;font-weight:bold;color:#ca8a04;">Target Market Share</h3><p style="font-size:32px;font-weight:bold;color:#a16207;margin-top:8px;">12%</p></div><div style="background:#fdf2f8;padding:20px;border-radius:12px;"><h3 style="font-size:16px;font-weight:bold;color:#db2777;">Customer Segments</h3><p style="font-size:32px;font-weight:bold;color:#be185d;margin-top:8px;">4</p></div></div></div>', '#ffffff'),
      s("s4", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#1e3a5f;border-bottom:3px solid #3b82f6;padding-bottom:8px;">Implementation Roadmap</h2><div style="margin-top:24px;"><div style="display:flex;gap:16px;margin-bottom:16px;"><div style="width:80px;height:80px;background:#3b82f6;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:14px;flex-shrink:0;">Q1</div><div><h3 style="font-weight:bold;font-size:16px;">Foundation & Quick Wins</h3><p style="color:#6b7280;font-size:14px;">Team assembly, baseline metrics, process audit</p></div></div><div style="display:flex;gap:16px;margin-bottom:16px;"><div style="width:80px;height:80px;background:#8b5cf6;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:14px;flex-shrink:0;">Q2-Q3</div><div><h3 style="font-weight:bold;font-size:16px;">Scale & Optimize</h3><p style="color:#6b7280;font-size:14px;">Digital platform launch, market expansion, partnerships</p></div></div><div style="display:flex;gap:16px;"><div style="width:80px;height:80px;background:#06b6d4;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:14px;flex-shrink:0;">Q4</div><div><h3 style="font-weight:bold;font-size:16px;">Measure & Iterate</h3><p style="color:#6b7280;font-size:14px;">Performance review, ROI analysis, next phase planning</p></div></div></div></div>', '#ffffff'),
    ]},

  { id: "company-profile", label: "Company Profile", category: "Business", title: "Company Profile", theme: "corporate",
    slides: [
      s("s1", '<div style="padding:60px;text-align:center;"><h1 style="font-size:44px;font-weight:bold;color:#111827;">Educo International</h1><p style="font-size:20px;color:#6b7280;margin-top:8px;">Transforming Education Across Africa</p><div style="width:80px;height:4px;background:#3b82f6;margin:24px auto;border-radius:2px;"></div><p style="font-size:14px;color:#9ca3af;">Company Profile · 2026</p></div>', '#ffffff'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#111827;">About Us</h2><p style="font-size:16px;color:#4b5563;line-height:1.8;margin-top:16px;">Educo International is a leading education technology company serving over 500 schools across 12 African countries. Founded in 2020, we provide comprehensive school management solutions that empower administrators, teachers, students, and parents.</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:32px;text-align:center;"><div style="background:#f3f4f6;padding:20px;border-radius:12px;"><p style="font-size:28px;font-weight:bold;color:#2563eb;">500+</p><p style="font-size:12px;color:#6b7280;">Schools</p></div><div style="background:#f3f4f6;padding:20px;border-radius:12px;"><p style="font-size:28px;font-weight:bold;color:#2563eb;">12</p><p style="font-size:12px;color:#6b7280;">Countries</p></div><div style="background:#f3f4f6;padding:20px;border-radius:12px;"><p style="font-size:28px;font-weight:bold;color:#2563eb;">250K+</p><p style="font-size:12px;color:#6b7280;">Students</p></div></div></div>', '#ffffff'),
    ]},

  { id: "go-to-market", label: "Go-To-Market", category: "Business", title: "Go-To-Market Strategy", theme: "modern",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:40px;font-weight:bold;color:#7c3aed;">Go-To-Market Strategy</h1><p style="font-size:18px;color:#a78bfa;margin-top:12px;">Product Launch Playbook · 2026</p></div>', 'linear-gradient(135deg, #faf5ff, #ede9fe)'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#7c3aed;">Target Market Segments</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px;"><div style="border:2px solid #ddd6fe;padding:20px;border-radius:12px;"><h3 style="color:#7c3aed;font-weight:bold;">Primary: K-12 Schools</h3><p style="font-size:14px;color:#6b7280;margin-top:8px;">Private and public schools with 200-2000 students seeking digital transformation.</p></div><div style="border:2px solid #ddd6fe;padding:20px;border-radius:12px;"><h3 style="color:#7c3aed;font-weight:bold;">Secondary: Universities</h3><p style="font-size:14px;color:#6b7280;margin-top:8px;">Tertiary institutions requiring comprehensive student management.</p></div></div></div>', '#ffffff'),
    ]},

  // ═══ MARKETING ═══
  { id: "marketing-plan", label: "Annual Marketing Plan", category: "Marketing", title: "Annual Marketing Plan 2026", theme: "vibrant",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:42px;font-weight:bold;color:white;">Annual Marketing Plan</h1><p style="font-size:20px;color:rgba(255,255,255,0.8);margin-top:12px;">2026 Strategy & Execution</p></div>', 'linear-gradient(135deg, #1e40af, #7c3aed)'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#1e40af;">Marketing Objectives</h2><div style="margin-top:20px;"><div style="display:flex;align-items:center;gap:16px;margin-bottom:16px;padding:16px;background:#eff6ff;border-radius:12px;"><div style="width:48px;height:48px;background:#2563eb;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:18px;">1</div><div><h3 style="font-weight:bold;">Increase Brand Awareness</h3><p style="color:#6b7280;font-size:14px;">Grow social media following by 200% across all platforms</p></div></div><div style="display:flex;align-items:center;gap:16px;margin-bottom:16px;padding:16px;background:#f0fdf4;border-radius:12px;"><div style="width:48px;height:48px;background:#16a34a;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:18px;">2</div><div><h3 style="font-weight:bold;">Generate 5,000 Qualified Leads</h3><p style="color:#6b7280;font-size:14px;">Through content marketing, webinars, and partnerships</p></div></div><div style="display:flex;align-items:center;gap:16px;padding:16px;background:#fefce8;border-radius:12px;"><div style="width:48px;height:48px;background:#ca8a04;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:18px;">3</div><div><h3 style="font-weight:bold;">Achieve 25% Conversion Rate</h3><p style="color:#6b7280;font-size:14px;">Optimize sales funnel with A/B testing and personalization</p></div></div></div></div>', '#ffffff'),
    ]},

  { id: "pitch-deck-startup", label: "Startup Pitch Deck", category: "Marketing", title: "Startup Pitch Deck", theme: "bold",
    slides: [
      s("s1", '<div style="padding:60px;text-align:center;"><h1 style="font-size:48px;font-weight:900;color:white;">EduConnect</h1><p style="font-size:20px;color:rgba(255,255,255,0.9);margin-top:12px;">Democratizing Quality Education in Africa</p><p style="font-size:14px;color:rgba(255,255,255,0.6);margin-top:32px;">Series A Fundraise · $5M</p></div>', 'linear-gradient(135deg, #0f172a, #1e3a5f)'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:32px;font-weight:bold;color:#0f172a;">The Problem</h2><p style="font-size:18px;color:#4b5563;line-height:1.8;margin-top:16px;">70% of secondary students in Sub-Saharan Africa lack access to quality supplementary education. Private tutoring costs ₦50,000+/month — unaffordable for most families.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;padding:16px;border-radius:0 8px 8px 0;margin-top:24px;"><p style="font-size:16px;color:#991b1b;font-weight:bold;">152 million children out of school across Africa</p><p style="font-size:13px;color:#6b7280;">— UNESCO, 2025</p></div></div>', '#ffffff'),
      s("s3", '<div style="padding:48px;"><h2 style="font-size:32px;font-weight:bold;color:#0f172a;">The Ask</h2><div style="text-align:center;margin-top:32px;"><p style="font-size:48px;font-weight:900;color:#2563eb;">$5M Series A</p><p style="font-size:16px;color:#6b7280;margin-top:8px;">18-month runway to profitability</p></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:32px;"><div style="text-align:center;padding:16px;"><p style="font-size:24px;font-weight:bold;color:#111827;">40%</p><p style="font-size:13px;color:#6b7280;">Product & Engineering</p></div><div style="text-align:center;padding:16px;"><p style="font-size:24px;font-weight:bold;color:#111827;">35%</p><p style="font-size:13px;color:#6b7280;">Sales & Marketing</p></div><div style="text-align:center;padding:16px;"><p style="font-size:24px;font-weight:bold;color:#111827;">25%</p><p style="font-size:13px;color:#6b7280;">Operations & Hiring</p></div></div></div>', '#ffffff'),
    ]},

  { id: "pitch-deck-executive", label: "Executive Pitch Deck", category: "Marketing", title: "Executive Pitch Deck", theme: "elegant",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:40px;font-weight:300;letter-spacing:2px;color:#111827;">EXECUTIVE BRIEFING</h1><div style="width:60px;height:2px;background:#111827;margin-top:16px;"></div><p style="font-size:16px;color:#6b7280;margin-top:16px;">Board of Directors · Q1 2026</p></div>', '#ffffff'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:24px;font-weight:300;letter-spacing:1px;color:#111827;border-bottom:1px solid #e5e7eb;padding-bottom:12px;">KEY PERFORMANCE INDICATORS</h2><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:24px;margin-top:24px;"><div style="padding:24px;border:1px solid #e5e7eb;border-radius:8px;"><p style="font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Revenue</p><p style="font-size:32px;font-weight:bold;color:#111827;">₦890M</p><p style="font-size:13px;color:#16a34a;">↑ 34% YoY</p></div><div style="padding:24px;border:1px solid #e5e7eb;border-radius:8px;"><p style="font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Active Users</p><p style="font-size:32px;font-weight:bold;color:#111827;">250K</p><p style="font-size:13px;color:#16a34a;">↑ 52% YoY</p></div></div></div>', '#ffffff'),
    ]},

  // ═══ PLANNING ═══
  { id: "project-timeline", label: "Project Timeline", category: "Planning", title: "Project Timeline", theme: "clean",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:36px;font-weight:bold;color:#0f172a;">Project Timeline</h1><p style="font-size:16px;color:#64748b;margin-top:8px;">Q1–Q4 2026 Implementation Plan</p></div>', '#f1f5f9'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:24px;font-weight:bold;color:#0f172a;">Implementation Phases</h2><div style="position:relative;margin-top:32px;padding-left:24px;border-left:3px solid #3b82f6;"><div style="margin-bottom:32px;"><div style="position:absolute;left:-9px;width:18px;height:18px;background:#3b82f6;border-radius:50%;"></div><h3 style="font-weight:bold;color:#1e40af;">Phase 1: Research (Jan–Feb)</h3><p style="font-size:14px;color:#6b7280;">Market research, user interviews, competitive analysis</p></div><div style="margin-bottom:32px;"><div style="position:absolute;left:-9px;width:18px;height:18px;background:#8b5cf6;border-radius:50%;margin-top:0;"></div><h3 style="font-weight:bold;color:#6d28d9;">Phase 2: Design (Mar–May)</h3><p style="font-size:14px;color:#6b7280;">Wireframes, prototyping, user testing</p></div><div style="margin-bottom:32px;"><div style="position:absolute;left:-9px;width:18px;height:18px;background:#06b6d4;border-radius:50%;"></div><h3 style="font-weight:bold;color:#0891b2;">Phase 3: Development (Jun–Sep)</h3><p style="font-size:14px;color:#6b7280;">Core platform build, API integration, QA</p></div><div><div style="position:absolute;left:-9px;width:18px;height:18px;background:#16a34a;border-radius:50%;"></div><h3 style="font-weight:bold;color:#15803d;">Phase 4: Launch (Oct–Dec)</h3><p style="font-size:14px;color:#6b7280;">Beta testing, soft launch, full rollout</p></div></div></div>', '#ffffff'),
    ]},

  { id: "product-roadmap", label: "Product Roadmap", category: "Planning", title: "Product Roadmap 2026", theme: "modern",
    slides: [
      s("s1", '<div style="padding:60px;text-align:center;"><h1 style="font-size:40px;font-weight:bold;color:#7c3aed;">Product Roadmap</h1><p style="font-size:18px;color:#a78bfa;">2026 Feature Pipeline</p></div>', 'linear-gradient(135deg, #faf5ff, #f5f3ff)'),
      s("s2", '<div style="padding:40px;"><h2 style="font-size:24px;font-weight:bold;color:#7c3aed;">Feature Priorities</h2><div style="margin-top:20px;"><div style="display:flex;gap:12px;margin-bottom:12px;"><span style="background:#7c3aed;color:white;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:bold;">P0</span><div><h3 style="font-weight:bold;font-size:15px;">Real-time Collaboration</h3><p style="font-size:13px;color:#6b7280;">Multiple users editing simultaneously</p></div></div><div style="display:flex;gap:12px;margin-bottom:12px;"><span style="background:#2563eb;color:white;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:bold;">P1</span><div><h3 style="font-weight:bold;font-size:15px;">AI Writing Assistant</h3><p style="font-size:13px;color:#6b7280;">Smart suggestions and auto-completion</p></div></div><div style="display:flex;gap:12px;"><span style="background:#16a34a;color:white;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:bold;">P2</span><div><h3 style="font-weight:bold;font-size:15px;">Offline Mode</h3><p style="font-size:13px;color:#6b7280;">Full functionality without internet</p></div></div></div></div>', '#ffffff'),
    ]},

  // ═══ INFOGRAPHICS ═══
  { id: "swot-analysis", label: "SWOT Analysis", category: "Infographics", title: "SWOT Analysis", theme: "clean",
    slides: [
      s("s1", '<div style="padding:48px;text-align:center;"><h1 style="font-size:36px;font-weight:bold;color:#111827;">SWOT Analysis</h1><p style="font-size:16px;color:#6b7280;">Strategic Assessment · 2026</p></div>', '#f9fafb'),
      s("s2", '<div style="padding:32px;"><h2 style="font-size:24px;font-weight:bold;text-align:center;color:#111827;margin-bottom:20px;">SWOT Matrix</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div style="background:#dcfce7;padding:20px;border-radius:12px;"><h3 style="color:#16a34a;font-weight:bold;font-size:16px;">Strengths</h3><ul style="font-size:13px;color:#374151;margin-top:8px;padding-left:16px;"><li>Market-leading technology</li><li>Strong brand recognition</li><li>Experienced team</li></ul></div><div style="background:#fef9c3;padding:20px;border-radius:12px;"><h3 style="color:#ca8a04;font-weight:bold;font-size:16px;">Weaknesses</h3><ul style="font-size:13px;color:#374151;margin-top:8px;padding-left:16px;"><li>Limited geographic reach</li><li>High customer acquisition cost</li><li>Dependency on key partners</li></ul></div><div style="background:#dbeafe;padding:20px;border-radius:12px;"><h3 style="color:#2563eb;font-weight:bold;font-size:16px;">Opportunities</h3><ul style="font-size:13px;color:#374151;margin-top:8px;padding-left:16px;"><li>Growing EdTech market</li><li>Government digitization push</li><li>Untapped rural markets</li></ul></div><div style="background:#fee2e2;padding:20px;border-radius:12px;"><h3 style="color:#dc2626;font-weight:bold;font-size:16px;">Threats</h3><ul style="font-size:13px;color:#374151;margin-top:8px;padding-left:16px;"><li>New market entrants</li><li>Regulatory changes</li><li>Economic instability</li></ul></div></div></div>', '#ffffff'),
    ]},

  { id: "process-flow", label: "Process Flow", category: "Infographics", title: "Process Flow Diagram", theme: "clean",
    slides: [
      s("s1", '<div style="padding:60px;text-align:center;"><h1 style="font-size:36px;font-weight:bold;color:#0f172a;">Process Flow</h1><p style="font-size:16px;color:#64748b;">Student Admission Process</p></div>', '#f8fafc'),
      s("s2", '<div style="padding:40px;"><h2 style="font-size:24px;font-weight:bold;color:#0f172a;text-align:center;">Admission Workflow</h2><div style="display:flex;align-items:center;justify-content:center;gap:8px;margin-top:32px;flex-wrap:wrap;"><div style="background:#3b82f6;color:white;padding:12px 20px;border-radius:8px;font-size:13px;font-weight:bold;text-align:center;">Application<br/>Submitted</div><div style="font-size:20px;color:#9ca3af;">→</div><div style="background:#8b5cf6;color:white;padding:12px 20px;border-radius:8px;font-size:13px;font-weight:bold;text-align:center;">Document<br/>Review</div><div style="font-size:20px;color:#9ca3af;">→</div><div style="background:#06b6d4;color:white;padding:12px 20px;border-radius:8px;font-size:13px;font-weight:bold;text-align:center;">Entrance<br/>Assessment</div><div style="font-size:20px;color:#9ca3af;">→</div><div style="background:#f59e0b;color:white;padding:12px 20px;border-radius:8px;font-size:13px;font-weight:bold;text-align:center;">Interview</div><div style="font-size:20px;color:#9ca3af;">→</div><div style="background:#16a34a;color:white;padding:12px 20px;border-radius:8px;font-size:13px;font-weight:bold;text-align:center;">Admission<br/>Decision</div></div></div>', '#ffffff'),
    ]},

  // ═══ EDUCATION ═══
  { id: "lecture-slides", label: "Lecture Slides", category: "Education", title: "Lecture Presentation", theme: "academic",
    slides: [
      s("s1", '<div style="padding:60px;"><h1 style="font-size:36px;font-weight:bold;color:#1e3a5f;">Introduction to Economics</h1><p style="font-size:18px;color:#64748b;margin-top:8px;">Chapter 3: Supply and Demand</p><p style="font-size:14px;color:#9ca3af;margin-top:24px;">Mrs. Adeyemi · SS2 Economics · Week 8</p></div>', '#f0f9ff'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#1e3a5f;">Learning Objectives</h2><div style="margin-top:20px;font-size:16px;line-height:2;"><p>By the end of this lesson, you should be able to:</p><ul style="margin-top:12px;padding-left:20px;"><li>Define supply, demand, and market equilibrium</li><li>Explain the law of demand and the law of supply</li><li>Draw and interpret supply and demand curves</li><li>Identify factors that shift supply and demand</li></ul></div></div>', '#ffffff'),
    ]},

  { id: "school-assembly", label: "School Assembly", category: "Education", title: "Weekly Assembly Presentation", theme: "bright",
    slides: [
      s("s1", '<div style="padding:60px;text-align:center;"><h1 style="font-size:40px;font-weight:bold;color:white;">Good Morning, Educo!</h1><p style="font-size:20px;color:rgba(255,255,255,0.9);margin-top:12px;">Weekly Assembly · March 18, 2026</p></div>', 'linear-gradient(135deg, #2563eb, #7c3aed)'),
      s("s2", '<div style="padding:48px;"><h2 style="font-size:28px;font-weight:bold;color:#2563eb;">This Week\'s Highlights</h2><ul style="font-size:16px;line-height:2.2;margin-top:16px;color:#374151;"><li>🏆 Congratulations to SS3 for winning the inter-class debate</li><li>📚 Library now has 5,000+ digital books available</li><li>⚽ Inter-house sports day practice begins Wednesday</li><li>🎨 Art exhibition submissions due by Friday</li></ul></div>', '#ffffff'),
    ]},
];

export const SLIDE_TEMPLATE_CATEGORIES = [...new Set(SLIDE_TEMPLATES.map(t => t.category))];

export const SLIDE_CATEGORY_COLORS: Record<string, string> = {
  "Business": "#1e40af",
  "Marketing": "#7c3aed",
  "Planning": "#0891b2",
  "Infographics": "#16a34a",
  "Education": "#f59e0b",
};
