export interface DocLanguage {
  tag: string;
  label: string;
}

/**
 * A comprehensive language list (English labels) used when the runtime
 * doesn't support `Intl.supportedValuesOf("language")`.
 *
 * Source basis: ISO 639-1 language names + a handful of common script/region variants.
 */
export const DOC_LANGUAGES: DocLanguage[] = [
  { tag: "af", label: "Afrikaans" },
  { tag: "sq", label: "Albanian" },
  { tag: "am", label: "Amharic" },
  { tag: "ar", label: "Arabic" },
  { tag: "hy", label: "Armenian" },
  { tag: "as", label: "Assamese" },
  { tag: "az", label: "Azerbaijani" },
  { tag: "eu", label: "Basque" },
  { tag: "be", label: "Belarusian" },
  { tag: "bn", label: "Bangla" },
  { tag: "bs", label: "Bosnian" },
  { tag: "bg", label: "Bulgarian" },
  { tag: "my", label: "Burmese" },
  { tag: "ca", label: "Catalan" },
  { tag: "ceb", label: "Cebuano" },
  { tag: "ny", label: "Chichewa" },
  { tag: "zh", label: "Chinese" },
  { tag: "zh-Hans", label: "Chinese (Simplified)" },
  { tag: "zh-Hant", label: "Chinese (Traditional)" },
  { tag: "co", label: "Corsican" },
  { tag: "hr", label: "Croatian" },
  { tag: "cs", label: "Czech" },
  { tag: "da", label: "Danish" },
  { tag: "dv", label: "Divehi" },
  { tag: "nl", label: "Dutch" },
  { tag: "en", label: "English" },
  { tag: "en-US", label: "English (United States)" },
  { tag: "en-GB", label: "English (United Kingdom)" },
  { tag: "eo", label: "Esperanto" },
  { tag: "et", label: "Estonian" },
  { tag: "tl", label: "Filipino" },
  { tag: "fi", label: "Finnish" },
  { tag: "fr", label: "French" },
  { tag: "fr-CA", label: "French (Canada)" },
  { tag: "fy", label: "Frisian" },
  { tag: "gl", label: "Galician" },
  { tag: "ka", label: "Georgian" },
  { tag: "de", label: "German" },
  { tag: "el", label: "Greek" },
  { tag: "gn", label: "Guarani" },
  { tag: "gu", label: "Gujarati" },
  { tag: "ht", label: "Haitian Creole" },
  { tag: "ha", label: "Hausa" },
  { tag: "haw", label: "Hawaiian" },
  { tag: "he", label: "Hebrew" },
  { tag: "hi", label: "Hindi" },
  { tag: "hmn", label: "Hmong" },
  { tag: "hu", label: "Hungarian" },
  { tag: "is", label: "Icelandic" },
  { tag: "ig", label: "Igbo" },
  { tag: "id", label: "Indonesian" },
  { tag: "ga", label: "Irish" },
  { tag: "it", label: "Italian" },
  { tag: "ja", label: "Japanese" },
  { tag: "jv", label: "Javanese" },
  { tag: "kn", label: "Kannada" },
  { tag: "kk", label: "Kazakh" },
  { tag: "km", label: "Khmer" },
  { tag: "rw", label: "Kinyarwanda" },
  { tag: "ko", label: "Korean" },
  { tag: "ku", label: "Kurdish" },
  { tag: "ky", label: "Kyrgyz" },
  { tag: "lo", label: "Lao" },
  { tag: "la", label: "Latin" },
  { tag: "lv", label: "Latvian" },
  { tag: "lt", label: "Lithuanian" },
  { tag: "lb", label: "Luxembourgish" },
  { tag: "mk", label: "Macedonian" },
  { tag: "mg", label: "Malagasy" },
  { tag: "ms", label: "Malay" },
  { tag: "ml", label: "Malayalam" },
  { tag: "mt", label: "Maltese" },
  { tag: "mi", label: "Māori" },
  { tag: "mr", label: "Marathi" },
  { tag: "mn", label: "Mongolian" },
  { tag: "ne", label: "Nepali" },
  { tag: "no", label: "Norwegian" },
  { tag: "or", label: "Odia" },
  { tag: "ps", label: "Pashto" },
  { tag: "fa", label: "Persian" },
  { tag: "pl", label: "Polish" },
  { tag: "pt", label: "Portuguese" },
  { tag: "pt-BR", label: "Portuguese (Brazil)" },
  { tag: "pt-PT", label: "Portuguese (Portugal)" },
  { tag: "pa", label: "Punjabi" },
  { tag: "ro", label: "Romanian" },
  { tag: "ru", label: "Russian" },
  { tag: "sm", label: "Samoan" },
  { tag: "gd", label: "Scottish Gaelic" },
  { tag: "sr", label: "Serbian" },
  { tag: "sr-Latn", label: "Serbian (Latin)" },
  { tag: "sn", label: "Shona" },
  { tag: "sd", label: "Sindhi" },
  { tag: "si", label: "Sinhala" },
  { tag: "sk", label: "Slovak" },
  { tag: "sl", label: "Slovenian" },
  { tag: "so", label: "Somali" },
  { tag: "st", label: "Southern Sotho" },
  { tag: "es", label: "Spanish" },
  { tag: "es-419", label: "Spanish (Latin America)" },
  { tag: "su", label: "Sundanese" },
  { tag: "sw", label: "Swahili" },
  { tag: "sv", label: "Swedish" },
  { tag: "tg", label: "Tajik" },
  { tag: "ta", label: "Tamil" },
  { tag: "tt", label: "Tatar" },
  { tag: "te", label: "Telugu" },
  { tag: "th", label: "Thai" },
  { tag: "tr", label: "Turkish" },
  { tag: "tk", label: "Turkmen" },
  { tag: "uk", label: "Ukrainian" },
  { tag: "ur", label: "Urdu" },
  { tag: "ug", label: "Uyghur" },
  { tag: "uz", label: "Uzbek" },
  { tag: "vi", label: "Vietnamese" },
  { tag: "cy", label: "Welsh" },
  { tag: "xh", label: "Xhosa" },
  { tag: "yi", label: "Yiddish" },
  { tag: "yo", label: "Yoruba" },
  { tag: "zu", label: "Zulu" },
];

