// THE DISTINCT SECTION STRUCTURES real sites use — from the `layout` column of docs/layout-benchmark/pages.tsv.
// Every section of every crawled page is reduced to a structure (row/grid/stack · how many · proportions in buckets ·
// nested columns), counted, and ranked; the cumulative share says how many structures cover 80 / 95 / 99 % of use.
// Writes docs/layout-benchmark/STRUCTURES.md (+ structures.json for the UAT harness).
//   node scripts/research/structures.js
const fs = require('fs'); const path = require('path');
const DIR = path.join(__dirname, '..', '..', 'docs', 'layout-benchmark');
const rows = fs.readFileSync(path.join(DIR, 'pages.tsv'), 'utf8').trim().split('\n');
const head = rows.shift().split('\t'); const L = head.indexOf('layout'), SITE = head.indexOf('site'), SRC = head.indexOf('source');

/** Proportions → the shape a designer would name them by: equal columns, or which side is wider and by how much. */
function ratio(shares) {
  const sum = shares.reduce((a, b) => a + b, 0) || 1; const p = shares.map((s) => (s / sum) * 100);
  const max = Math.max(...p), min = Math.min(...p);
  if (max - min <= 8) return 'equal';
  if (p.length === 2) { const w = Math.round(p[0] / 10) * 10; return `${w}/${100 - w}`; }
  return p.map((x) => Math.round(x / 10) * 10).join('/');
}
/** One section's layout string → its structure. */
function structure(layout) {
  const m = layout.match(/^(row|grid)(\d+)\[([\d/]+)\](\([\d/]+\))*(x\d+)?(\+stack)?/);
  if (m) {
    const n = +m[2]; const kind = m[1] === 'grid' ? 'grid' : 'row';
    const cols = n >= 6 ? '6+' : String(n);
    const rep = m[5] ? ' repeated' : '';
    const nested = m[4] ? ' +nested columns' : '';
    const withStack = m[6] ? ' +stacked parts' : '';
    return `${kind} of ${cols} (${n >= 6 ? 'many' : ratio(m[3].split('/').map(Number))})${nested}${rep}${withStack}`;
  }
  const s = layout.match(/^stack(\d*)(\{(.*)\})?/);
  if (s) {
    const inner = s[3] || '';
    const rowsIn = (inner.match(/(row|grid)\d/g) || []).length;
    return rowsIn ? `stack with ${rowsIn > 1 ? 'several rows' : 'a row'} inside` : 'plain stack (text, image, heading…)';
  }
  return layout === '·' ? 'single block' : 'other';
}

const count = new Map(); const eg = new Map(); let total = 0; const sticky = { n: 0 };
const widths = new Map();
for (const r of rows) {
  const c = r.split('\t'); const lay = c[L]; if (!lay) continue;
  for (const sec of lay.split(' > ')) {
    const [width, layout, st] = sec.split('|');
    const k = structure(layout || '');
    count.set(k, (count.get(k) || 0) + 1); total++;
    if (!eg.has(k)) eg.set(k, new Set()); if (eg.get(k).size < 4) eg.get(k).add(`${c[SITE]} (${c[SRC]})`);
    widths.set(width, (widths.get(width) || 0) + 1);
    if (st) sticky.n++;
  }
}
// EVERY row and grid, wherever it sits — top level or inside a stack. The section list above says "a stack with a row
// inside"; this says WHICH row, which is what the builder has to be able to make and resize.
const rowCount = new Map(); let rowTotal = 0;
for (const r of rows) {
  const lay = r.split('\t')[L]; if (!lay) continue;
  for (const m of lay.matchAll(/(row|grid)(\d+)\[([\d/]+)\]((?:\([\d/]+\))*)(x\d+)?/g)) {
    const k = structure(m[0]); rowCount.set(k, (rowCount.get(k) || 0) + 1); rowTotal++;
  }
}
const rowRanked = [...rowCount.entries()].sort((a, b) => b[1] - a[1]);
let rcum = 0; const rat = {};
const rowLines = rowRanked.map(([k, n], i) => { rcum += n; const pct = (rcum / rowTotal) * 100; for (const t of [80, 95, 99]) if (!rat[t] && pct >= t) rat[t] = i + 1; return `| ${i + 1} | ${k} | ${n} | ${((n / rowTotal) * 100).toFixed(1)}% | ${pct.toFixed(1)}% |`; });

const ranked = [...count.entries()].sort((a, b) => b[1] - a[1]);
let cum = 0; const at = {};
const lines = ranked.map(([k, n], i) => { cum += n; const pct = (cum / total) * 100; for (const t of [80, 95, 99]) if (!at[t] && pct >= t) at[t] = i + 1; return `| ${i + 1} | ${k} | ${n} | ${((n / total) * 100).toFixed(1)}% | ${pct.toFixed(1)}% | ${[...eg.get(k)].join(', ')} |`; });

const md = `# Section structures real sites use — distilled from the crawl

Generated by \`scripts/research/structures.js\` from \`pages.tsv\` (${rows.length} pages, **${total} sections**, 490 sites:
awwwards, Webflow and Framer). Each section is reduced to its structure; proportions are bucketed (±8% counts as equal).
**${ranked.length} distinct structures.** Coverage: **${at[80]} structures cover 80%** of all sections, **${at[95]} cover 95%**,
**${at[99]} cover 99%** (RULE Q: 80/20 first, then to the 99th percentile). Sections with something sticky inside:
${sticky.n} (${((sticky.n / total) * 100).toFixed(1)}%). Section width: ${[...widths.entries()].map(([w, n]) => `${w} ${((n / total) * 100).toFixed(0)}%`).join(' · ')}.

Every structure below must be buildable through the builder's UI and pass the resize sweep and the Preview check at
every size — \`scripts/uat/\` builds them from \`structures.json\`.

## Every row and grid, wherever it sits (${rowTotal} rows · ${rowRanked.length} shapes · 80% by ${rat[80]} · 95% by ${rat[95]} · 99% by ${rat[99]})

| # | Row / grid shape | Count | Share | Cumulative |
|---|---|---|---|---|
${rowLines.join("\n")}

## Whole sections

| # | Structure | Sections | Share | Cumulative | Examples |
|---|---|---|---|---|---|
${lines.join('\n')}
`;
fs.writeFileSync(path.join(DIR, 'STRUCTURES.md'), md);
fs.writeFileSync(path.join(DIR, 'rowshapes.json'), JSON.stringify(rowRanked.map(([shape, count]) => ({ shape, count })), null, 1));
fs.writeFileSync(path.join(DIR, 'structures.json'), JSON.stringify(ranked.map(([k, n]) => ({ structure: k, sections: n, examples: [...eg.get(k)] })), null, 1));
console.log(`rows: ${rowTotal} · ${rowRanked.length} shapes · 80% by ${rat[80]} · 95% by ${rat[95]} · 99% by ${rat[99]}`);
console.log(rowRanked.slice(0, 30).map(([k, n]) => `${String(n).padStart(6)}  ${k}`).join('\n'));
console.log(`${total} sections · ${ranked.length} structures · 80% by ${at[80]} · 95% by ${at[95]} · 99% by ${at[99]}`);
console.log(ranked.slice(0, 40).map(([k, n]) => `${String(n).padStart(6)}  ${k}`).join('\n'));
